/**
 * English display names for every skill id the client knows.
 *
 * Generated once from the `SkillID` enum GWCA distributes with GWToolbox++
 * under the MIT grant recorded in THIRD-PARTY-NOTICES.md. Names are derived
 * from the C++ identifiers, so a few read without their apostrophe
 * ("Dwaynas Kiss"); this being data rather than a parsed vendored header
 * means such a name can simply be corrected in place.
 *
 * The installed client stays authoritative for everything else — profession,
 * attribute, elite state, costs — which `skill-table.ts` reads from the
 * player's own binary. This supplies spelling only.
 */

/** Ids are positional: entry `n` names skill `n`; empty means "no name". */
const NAMES =
  "No Skill|Healing Signet|Resurrection Signet|Signet of Capture|BAMPH|"
  + "Power Block|Mantra of Earth|Mantra of Flame|Mantra of Frost|"
  + "Mantra of Lightning|Hex Breaker|Distortion|Mantra of Celerity|"
  + "Mantra of Recovery|Mantra of Persistence|Mantra of Inscriptions|"
  + "Mantra of Concentration|Mantra of Resolve|Mantra of Signets|Fragility|"
  + "Confusion|Inspired Enchantment|Inspired Hex|Power Spike|Power Leak|"
  + "Power Drain|Empathy|Shatter Delusions|Backfire|Blackout|Diversion|"
  + "Conjure Phantasm|Illusion of Weakness|Illusionary Weaponry|"
  + "Sympathetic Visage|Ignorance|Arcane Conundrum|Illusion of Haste|Channeling|"
  + "Energy Surge|Ether Feast|Ether Lord|Energy Burn|Clumsiness|Phantom Pain|"
  + "Ethereal Burden|Guilt|Ineptitude|Spirit of Failure|Mind Wrack|Wastrels Worry|"
  + "Shame|Panic|Migraine|Crippling Anguish|Fevered Dreams|Soothing Images|"
  + "Cry of Frustration|Signet of Midnight|Signet of Weariness|"
  + "Signet of Illusions beta version|Leech Signet|Signet of Humility|"
  + "Keystone Signet|Mimic|Arcane Mimicry|Spirit Shackles|Shatter Hex|"
  + "Drain Enchantment|Shatter Enchantment|Disappear|"
  + "Unnatural Signet alpha version|Elemental Resistance|Physical Resistance|Echo|"
  + "Arcane Echo|Imagined Burden|Chaos Storm|Epidemic|Energy Drain|Energy Tap|"
  + "Arcane Thievery|Mantra of Recall|Animate Bone Horror|Animate Bone Fiend|"
  + "Animate Bone Minions|Grenths Balance|Veratas Gaze|Veratas Aura|Deathly Chill|"
  + "Veratas Sacrifice|Well of Power|Well of Blood|Well of Suffering|"
  + "Well of the Profane|Putrid Explosion|Soul Feast|Necrotic Traversal|"
  + "Consume Corpse|Parasitic Bond|Soul Barbs|Barbs|Shadow Strike|"
  + "Price of Failure|Death Nova|Deathly Swarm|Rotting Flesh|Virulence|Suffering|"
  + "Life Siphon|Unholy Feast|Awaken the Blood|Desecrate Enchantments|"
  + "Tainted Flesh|Aura of the Lich|Blood Renewal|Dark Aura|Enfeeble|"
  + "Enfeebling Blood|Blood is Power|Blood of the Master|Spiteful Spirit|"
  + "Malign Intervention|Insidious Parasite|Spinal Shivers|Wither|Life Transfer|"
  + "Mark of Subversion|Soul Leech|Defile Flesh|Demonic Flesh|Barbed Signet|"
  + "Plague Signet|Dark Pact|Order of Pain|Faintheartedness|Shadow of Fear|"
  + "Rigor Mortis|Dark Bond|Infuse Condition|Malaise|Rend Enchantments|"
  + "Lingering Curse|Strip Enchantment|Chilblains|Signet of Agony|"
  + "Offering of Blood|Dark Fury|Order of the Vampire|Plague Sending|Mark of Pain|"
  + "Feast of Corruption|Taste of Death|Vampiric Gaze|Plague Touch|Vile Touch|"
  + "Vampiric Touch|Blood Ritual|Touch of Agony|Weaken Armor|Windborne Speed|"
  + "Lightning Storm|Gale|Whirlwind|Elemental Attunement|Armor of Earth|"
  + "Kinetic Armor|Eruption|Magnetic Aura|Earth Attunement|Earthquake|Stoning|"
  + "Stone Daggers|Grasping Earth|Aftershock|Ward Against Elements|"
  + "Ward Against Melee|Ward Against Foes|Ether Prodigy|Incendiary Bonds|"
  + "Aura of Restoration|Ether Renewal|Conjure Flame|Inferno|Fire Attunement|"
  + "Mind Burn|Fireball|Meteor|Flame Burst|Rodgorts Invocation|Mark of Rodgort|"
  + "Immolate|Meteor Shower|Phoenix|Flare|Lava Font|Searing Heat|Fire Storm|"
  + "Glyph of Elemental Power|Glyph of Energy|Glyph of Lesser Energy|"
  + "Glyph of Concentration|Glyph of Sacrifice|Glyph of Renewal|Rust|"
  + "Lightning Surge|Armor of Frost|Conjure Frost|Water Attunement|Mind Freeze|"
  + "Ice Prison|Ice Spikes|Frozen Burst|Shard Storm|Ice Spear|Maelstrom|Iron Mist|"
  + "Crystal Wave|Obsidian Flesh|Obsidian Flame|Blinding Flash|Conjure Lightning|"
  + "Lightning Strike|Chain Lightning|Enervating Charge|Air Attunement|Mind Shock|"
  + "Glimmering Mark|Thunderclap|Lightning Orb|Lightning Javelin|Shock|"
  + "Lightning Touch|Swirling Aura|Deep Freeze|Blurred Vision|Mist Form|"
  + "Water Trident|Armor of Mist|Ward Against Harm|Smite|Life Bond|"
  + "Balthazars Spirit|Strength of Honor|Life Attunement|Protective Spirit|"
  + "Divine Intervention|Symbol of Wrath|Retribution|Holy Wrath|Essence Bond|"
  + "Scourge Healing|Banish|Scourge Sacrifice|Vigorous Spirit|Watchful Spirit|"
  + "Blessed Aura|Aegis|Guardian|Shield of Deflection|Aura of Faith|"
  + "Shield of Regeneration|Shield of Judgment|Protective Bond|Pacifism|Amity|"
  + "Peace and Harmony|Judges Insight|Unyielding Aura|Mark of Protection|"
  + "Life Barrier|Zealots Fire|Balthazars Aura|Spell Breaker|Healing Seed|"
  + "Mend Condition|Restore Condition|Mend Ailment|Purge Conditions|"
  + "Divine Healing|Heal Area|Orison of Healing|Word of Healing|Dwaynas Kiss|"
  + "Divine Boon|Healing Hands|Heal Other|Heal Party|Healing Breeze|"
  + "Vital Blessing|Mending|Live Vicariously|Infuse Health|Signet of Devotion|"
  + "Signet of Judgment|Purge Signet|Bane Signet|Blessed Signet|Martyr|"
  + "Shielding Hands|Contemplation of Purity|Remove Hex|Smite Hex|Convert Hexes|"
  + "Light of Dwayna|Resurrect|Rebirth|Reversal of Fortune|Succor|Holy Veil|"
  + "Divine Spirit|Draw Conditions|Holy Strike|Healing Touch|Restore Life|"
  + "Vengeance|To the Limit|Battle Rage|Defy Pain|Rush|Hamstring|Wild Blow|"
  + "Power Attack|Desperation Blow|Thrill of Victory|Distracting Blow|"
  + "Protectors Strike|Griffons Sweep|Pure Strike|Skull Crack|Cyclone Axe|"
  + "Hammer Bash|Bulls Strike|I Will Avenge You|Axe Rake|Cleave|"
  + "Executioners Strike|Dismember|Eviscerate|Penetrating Blow|Disrupting Chop|"
  + "Swift Chop|Axe Twist|For Great Justice|Flurry|Defensive Stance|Frenzy|"
  + "Endure Pain|Watch Yourself|Sprint|Belly Smash|Mighty Blow|Crushing Blow|"
  + "Crude Swing|Earth Shaker|Devastating Hammer|Irresistible Blow|Counter Blow|"
  + "Backbreaker|Heavy Blow|Staggering Blow|Dolyak Signet|Warriors Cunning|"
  + "Shield Bash|Charge|Victory Is Mine|Fear Me|Shields Up|I Will Survive|"
  + "Dont Believe Their Lies|Berserker Stance|Balanced Stance|Gladiators Defense|"
  + "Deflect Arrows|Warriors Endurance|Dwarven Battle Stance|Disciplined Stance|"
  + "Wary Stance|Shield Stance|Bulls Charge|Bonettis Defense|Hundred Blades|"
  + "Sever Artery|Galrath Slash|Gash|Final Thrust|Seeking Blade|Riposte|"
  + "Deadly Riposte|Flourish|Savage Slash|Hunters Shot|Pin Down|Crippling Shot|"
  + "Power Shot|Barrage|Dual Shot|Quick Shot|Penetrating Attack|Distracting Shot|"
  + "Precision Shot|Splinter Shot monster skill|Determined Shot|Called Shot|"
  + "Poison Arrow|Oath Shot|Debilitating Shot|Point Blank Shot|Concussion Shot|"
  + "Punishing Shot|Call of Ferocity|Charm Animal|Call of Protection|"
  + "Call of Elemental Protection|Call of Vitality|Call of Haste|Call of Healing|"
  + "Call of Resilience|Call of Feeding|Call of the Hunter|Call of Brutality|"
  + "Call of Disruption|Revive Animal|Symbiotic Bond|Throw Dirt|Dodge|Savage Shot|"
  + "Antidote Signet|Incendiary Arrows|Melandrus Arrows|Marksmans Wager|"
  + "Ignite Arrows|Read the Wind|Kindle Arrows|Choking Gas|Apply Poison|"
  + "Comfort Animal|Bestial Pounce|Maiming Strike|Feral Lunge|Scavenger Strike|"
  + "Melandrus Assault|Ferocious Strike|Predators Pounce|Brutal Strike|"
  + "Disrupting Lunge|Troll Unguent|Otyughs Cry|Escape|Practiced Stance|"
  + "Whirling Defense|Melandrus Resilience|Dryders Defenses|Lightning Reflexes|"
  + "Tigers Fury|Storm Chaser|Serpents Quickness|Dust Trap|Barbed Trap|Flame Trap|"
  + "Healing Spring|Spike Trap|Winter|Winnowing|Edge of Extinction|"
  + "Greater Conflagration|Conflagration|Fertile Season|Symbiosis|Primal Echoes|"
  + "Predatory Season|Frozen Soil|Favorable Winds|High Winds|Energizing Wind|"
  + "Quickening Zephyr|Natures Renewal|Muddy Terrain|Bleeding|Blind|Burning|"
  + "Crippled|Deep Wound|Disease|Poison|Dazed|Weakness|Cleansed|"
  + "Eruption environment|Fire Storm environment|Vital Blessing monster skill|"
  + "Fount Of Maguuma|Healing Fountain|Icy Ground|Maelstrom environment|"
  + "Mursaat Tower skill|Quicksand environment effect|Curse of the Bloodstone|"
  + "Chain Lightning environment|Obelisk Lightning|Tar|Siege Attack|"
  + "Resurrect Party|Scepter of Orrs Aura|Scepter of Orrs Power|Burden Totem|"
  + "Splinter Mine skill|Entanglement|Dwarven Powder Keg|Seed of Resurrection|"
  + "Deafening Roar|Brutal Mauling|Crippling Attack|Charm Animal monster skill|"
  + "Breaking Charm|Charr Buff|Claim Resource|Claim Resource1|Claim Resource2|"
  + "Claim Resource3|Claim Resource4|Claim Resource5|Claim Resource6|"
  + "Claim Resource7|Dozen Shot|Nibble|Claim Resource8|Claim Resource9|Reflection|"
  + "Spectral Agony|Giant Stomp|Agnars Rage|Healing Breeze Agnars Rage|"
  + "Crystal Haze|Crystal Bonds|Jagged Crystal Skin|Crystal Hibernation|"
  + "Stun Immunity|Invulnerability|Hunger of the Lich|Embrace the Pain|"
  + "Life Vortex|Oracle Link|Guardian Pacify|Soul Vortex|Soul Vortex2|"
  + "Spectral Agony1|Natural Resistance|Natural Resistance1|Guild Lord Aura|"
  + "Critical Hit Probability|Stun on Critical Hit|Blood Splattering|"
  + "Inanimate Object|Undead sensitivity to Light|Energy Boost|Health Drain|"
  + "Immunity to Critical Hits|"
  + "Titans get plus Health regen and set enemies on fire each time he is hit|"
  + "Undying|Resurrect Gargoyle|Seal Regen|Lightning Orb1|"
  + "Wurm Siege Dunes of Despair|Wurm Siege|Claim Resource10|Shiver Touch|"
  + "Spontaneous Combustion|Vanish|Victory or Death|Mark of Insecurity|"
  + "Disrupting Dagger|Deadly Paradox|Teleport Players|"
  + "Quest skill for Coastal Exam|Holy Blessing|Statues Blessing|Siege Attack1|"
  + "Siege Attack2|Domain of Skill Damage|Domain of Energy Draining|"
  + "Domain of Elements|Domain of Health Draining|Domain of Slow|Divine Fire|"
  + "Swamp Water|Janthirs Gaze|Fake Spell|Charm Animal monster|Stormcaller skill|"
  + "Knock|Quest Skill|Rurik Must Live|Blessing of the Kurzicks|Lichs Phylactery|"
  + "Restore Life monster skill|Chimera of Intensity||||||||||||||||||||||||||||||"
  + "Life Draining||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||"
  + "Jaundiced Gaze|Wail of Doom|Heros Insight|Gaze of Contempt|"
  + "Berserkers Insight|Slayers Insight|Vipers Defense|Return|"
  + "Aura of Displacement|Generous Was Tsungrai|Mighty Was Vorizun|To the Death|"
  + "Death Blossom|Twisting Fangs|Horns of the Ox|Falling Spider|"
  + "Black Lotus Strike|Fox Fangs|Moebius Strike|Jagged Strike|"
  + "Unsuspecting Strike|Entangling Asp|Mark of Death|Iron Palm|Resilient Weapon|"
  + "Blind Was Mingson|Grasping Was Kuurong|Vengeful Was Khanhei|"
  + "Flesh of My Flesh|Splinter Weapon|Weapon of Warding|Wailing Weapon|"
  + "Nightmare Weapon|Sorrows Flame|Sorrows Fist|Blast Furnace|Beguiling Haze|"
  + "Enduring Toxin|Shroud of Silence|Expose Defenses|Power Leech|Arcane Languor|"
  + "Animate Vampiric Horror|Cultists Fervor||Reapers Mark|Shatterstone|"
  + "Protectors Defense|Run as One|Defiant Was Xinrae|Lyssas Aura|Shadow Refuge|"
  + "Scorpion Wire|Mirrored Stance|Discord|Well of Weariness|Vampiric Spirit|"
  + "Depravity|Icy Veins|Weaken Knees|Burning Speed|Lava Arrows|Bed of Coals|"
  + "Shadow Form|Siphon Strength|Vile Miasma|Veratas Promise|Ray of Judgment|"
  + "Primal Rage|Animate Flesh Golem|Borrowed Energy|Reckless Haste|Blood Bond|"
  + "Ride the Lightning|Energy Boon|Dwaynas Sorrow|Retreat|Poisoned Heart|"
  + "Fetid Ground|Arc Lightning|Gust|Churning Earth|Liquid Flame|Steam|"
  + "Boon Signet|Reverse Hex|Lacerating Chop|Fierce Blow|Sun and Moon Slash|"
  + "Splinter Shot|Melandrus Shot|Snare|Chomper|Kilroy Stonekin|"
  + "Adventurers Insight|Dancing Daggers|Conjure Nightmare|Signet of Disruption|"
  + "Dissipation|Ravenous Gaze|Order of Apostasy|Oppressive Gaze|Lightning Hammer|"
  + "Vapor Blade|Healing Light|Aim True|Coward|Pestilence|Shadowsong|"
  + "Shadowsong attack|Resurrect monster skill|Consuming Flames|"
  + "Chains of Enslavement|Signet of Shadows|Lyssas Balance|Visions of Regret|"
  + "Illusion of Pain|Stolen Speed|Ether Signet|Signet of Disenchantment|"
  + "Vocal Minority|Searing Flames|Shield Guardian|Restful Breeze|"
  + "Signet of Rejuvenation|Whirling Axe|Forceful Blow|Headshot|None Shall Pass|"
  + "Quivering Blade|Seeking Arrows|Rampagers Insight|Hunters Insight|"
  + "Amulet of Protection|Oath of Healing|Overload|Images of Remorse|"
  + "Shared Burden|Soul Bind|Blood of the Aggressor|Icy Prism|Furious Axe|"
  + "Auspicious Blow|On Your Knees|Dragon Slash|Marauders Shot|Focused Shot|"
  + "Spirit Rift|Union|Blessing of the Kurzicks1|Tranquil Was Tanasen|"
  + "Consume Soul|Spirit Light|Lamentation|Rupture Soul|Spirit to Flesh|"
  + "Spirit Burn|Destruction|Dissonance|Dissonance attack|Disenchantment|"
  + "Disenchantment attack|Recall|Sharpen Daggers|Shameful Fear|Shadow Shroud|"
  + "Shadow of Haste|Auspicious Incantation|Power Return|Complicate|Shatter Storm|"
  + "Unnatural Signet|Rising Bile|Envenom Enchantments|Shockwave|"
  + "Ward of Stability|Icy Shackles|Cry of Lament|Blessed Light|Withdraw Hexes|"
  + "Extinguish|Signet of Strength|With Haste|Trappers Focus|Brambles|"
  + "Desperate Strike|Way of the Fox|Shadowy Burden|Siphon Speed|Deaths Charge|"
  + "Power Flux|Expel Hexes|Rip Enchantment|Energy Font|Spell Shield|"
  + "Healing Whisper|Ethereal Light|Release Enchantments|Lacerate|Spirit Transfer|"
  + "Restoration|Vengeful Weapon|Archemorus Strike|Spear of Archemorus Level 1|"
  + "Spear of Archemorus Level 2|Spear of Archemorus Level 3|"
  + "Spear of Archemorus Level 4|Spear of Archemorus Level 5|Argos Cry|Jade Fury|"
  + "Blinding Powder|Mantis Touch|Exhausting Assault|Repeating Strike|"
  + "Way of the Lotus|Mark of Instability|Mistrust|Feast of Souls|Recuperation|"
  + "Shelter|Weapon of Shadow|Torch Enchantment|Caltrops|Nine Tail Strike|"
  + "Way of the Empty Palm|Temple Strike|Golden Phoenix Strike|"
  + "Expunge Enchantments|Deny Hexes|Triple Chop|Enraged Smash|Renewing Smash|"
  + "Tiger Stance|Standing Slash|Famine|Torch Hex|Torch Degeneration Hex|"
  + "Blinding Snow|Avalanche skill|Snowball|Mega Snowball|Yuletide|Ice Skates|"
  + "Ice Fort|Yellow Snow|Hidden Rock|Snow Down the Shirt|Mmmm Snowcone|"
  + "Holiday Blues|Icicles|Ice Breaker|Lets Get Em|Flurry of Ice|Snowball NPC|"
  + "Undying1|Critical Eye|Critical Strike|Blades of Steel|Jungle Strike|"
  + "Wild Strike|Leaping Mantis Sting|Black Mantis Thrust|Disrupting Stab|"
  + "Golden Lotus Strike|Critical Defenses|Way of Perfection|Dark Apostasy|"
  + "Locusts Fury|Shroud of Distress|Heart of Shadow|Impale|Seeping Wound|"
  + "Assassins Promise|Signet of Malice|Dark Escape|Crippling Dagger|Star Strike|"
  + "Spirit Walk|Unseen Fury|Flashing Blades|Dash|Dark Prison|Palm Strike|"
  + "Assassin of Lyssa|Mesmer of Lyssa|Revealed Enchantment|Revealed Hex|"
  + "Disciple of Energy|Empathy Koro|Accumulated Pain|Psychic Distraction|"
  + "Ancestors Visage|Recurring Insecurity|Kitahs Burden|Psychic Instability|"
  + "Chaotic Power|Hex Eater Signet|Celestial Haste|Feedback|Arcane Larceny|"
  + "Chaotic Ward|Favor of the Gods|Dark Aura blessing|Spoil Victor|"
  + "Lifebane Strike|Bitter Chill|Taste of Pain|Defile Enchantments|"
  + "Shivers of Dread|Star Servant|Necromancer of Grenth|Ritualist of Grenth|"
  + "Vampiric Swarm|Blood Drinker|Vampiric Bite|Wallows Bite|Enfeebling Touch|"
  + "Disciple of Ice|Teinais Wind|Shock Arrow|Unsteady Ground|Sliver Armor|"
  + "Ash Blast|Dragons Stomp|Unnatural Resistance|Second Wind|Cloak of Faith|"
  + "Smoldering Embers|Double Dragon|Disciple of the Air|Teinais Heat|"
  + "Breath of Fire|Star Burst|Glyph of Essence|Teinais Prison|Mirror of Ice|"
  + "Teinais Crystals|Celestial Storm|Monk of Dwayna|Aura of the Grove|"
  + "Cathedral Collapse|Miasma|Acid Trap|Shield of Saint Viktor|"
  + "Urn of Saint Viktor Level 1|Urn of Saint Viktor Level 2|"
  + "Urn of Saint Viktor Level 3|Urn of Saint Viktor Level 4|"
  + "Urn of Saint Viktor Level 5|Aura of Light|Kirins Wrath|Spirit Bond|"
  + "Air of Enchantment|Warriors Might|Heavens Delight|Healing Burst|"
  + "Kareis Healing Circle|Jameis Gaze|Gift of Health|Battle Fervor|Life Sheath|"
  + "Star Shine|Disciple of Fire|Empathic Removal|Warrior of Balthazar|"
  + "Resurrection Chant|Word of Censure|Spear of Light|Stonesoul Strike|"
  + "Shielding Branches|Drunken Blow|Leviathans Sweep|Jaizhenju Strike|"
  + "Penetrating Chop|Yeti Smash|Disciple of the Earth|Ranger of Melandru|"
  + "Storm of Swords|You Will Die|Auspicious Parry|Strength of the Oak|"
  + "Silverwing Slash|Destroy Enchantment|Shove|Base Defense|Carrier Defense|"
  + "The Chalice of Corruption||Song of the Mists|Demonic Agility|"
  + "Blessing of the Kirin|Emperor Degen|Juggernaut Toss|Aura of the Juggernaut|"
  + "Star Shards|||||||||||||||Turtle Shell|Exposed Underbelly|"
  + "Cathedral Collapse1|Blood of zu Heltzer|Afflicted Soul Explosion|"
  + "Invincibility|Last Stand|Dark Chain Lightning|Seadragon Health Trigger|"
  + "Corrupted Breath|Renewing Corruption|Corrupted Dragon Spores|"
  + "Corrupted Dragon Scales|Construct Possession|"
  + "Siege Turtle Attack The Eternal Grove|Siege Turtle Attack Fort Aspenwood|"
  + "Siege Turtle Attack Gyala Hatchery|Of Royal Blood|Passage to Tahnnakai|"
  + "Sundering Attack|Zojuns Shot|Consume Spirit|Predatory Bond|Heal as One|"
  + "Zojuns Haste|Needling Shot|Broad Head Arrow|Glass Arrows|Archers Signet|"
  + "Savage Pounce|Enraged Lunge|Bestial Mauling|Energy Drain effect|"
  + "Poisonous Bite|Pounce|Celestial Stance|Sheer Exhaustion|Bestial Fury|"
  + "Life Drain|Vipers Nest|Equinox|Tranquility|Acute Weakness|Clamor of Souls||"
  + "Ritual Lord|Cruel Was Daoshen|Protective Was Kaolai|Attuned Was Songkai|"
  + "Resilient Was Xiko|Lively Was Naomei|Anguished Was Lingwah|Draw Spirit|"
  + "Channeled Strike|Spirit Boon Strike|Essence Strike|Spirit Siphon|"
  + "Explosive Growth|Boon of Creation|Spirit Channeling|Armor of Unfeeling|"
  + "Soothing Memories|Mend Body and Soul|Dulled Weapon|Binding Chains|"
  + "Painful Bond|Signet of Creation|Signet of Spirits|Soul Twisting|"
  + "Celestial Summoning|Archemorus Strike Celestial Summoning|"
  + "Shield of Saint Viktor Celestial Summoning|Ghostly Haste|Gaze from Beyond|"
  + "Ancestors Rage|Pain|Pain attack|Displacement|Preservation|Life|Earthbind|"
  + "Bloodsong|Bloodsong attack|Wanderlust|Wanderlust attack|Spirit Light Weapon|"
  + "Brutal Weapon|Guided Weapon|Meekness|Frigid Armor|Healing Ring|Renew Life|"
  + "Doom|Wielders Boon|Soothing|Vital Weapon|Weapon of Quickening|Signet of Rage|"
  + "Fingers of Chaos|Echoing Banishment|Suicidal Impulse|Impossible Odds|"
  + "Battle Scars|Riposting Shadows|Meditation of the Reaper|Battle Cry|"
  + "Elemental Defense Zone|Melee Defense Zone|Blessed Water|Defiled Water|"
  + "Stone Spores|Turret Arrow|Blood Flower skill|Fire Flower skill|"
  + "Poison Arrow flower|Haiju Lagoon Water|Aspect of Exhaustion|"
  + "Aspect of Exposure|Aspect of Surrender|Aspect of Death|Aspect of Soothing|"
  + "Aspect of Pain|Aspect of Lethargy|Aspect of Depletion energy loss|"
  + "Aspect of Failure|Aspect of Shadows|Scorpion Aspect|Aspect of Fear|"
  + "Aspect of Depletion energy depletion damage|Aspect of Decay|"
  + "Aspect of Torment|Nightmare Aspect|Spiked Coral|Shielding Urn skill|"
  + "Extensive Plague Exposure|Forests Binding|Exploding Spores|Suicide Energy|"
  + "Suicide Health|Nightmare Refuge|Oni Health Lock|Oni Shadow Health Lock|"
  + "Signet of Attainment|Rage of the Sea|Meditation of the Reaper1||"
  + "Fireball obelisk|Final Thrust1||||Sugar Rush medium|Torment Slash|"
  + "Spirit of the Festival|Trade Winds|Dragon Blast|Imperial Majesty|"
  + "Monster doesnt get death penalty|Twisted Spikes|Marble Trap|Shadow Tripwire|"
  + "Extend Conditions|Hypochondria|Wastrels Demise|Spiritual Pain|"
  + "Drain Delusions|Persistence of Memory|Symbols of Inspiration|"
  + "Symbolic Celerity|Frustration|Tease|Ether Phantom|Web of Disruption|"
  + "Enchanters Conundrum|Signet of Illusions|Discharge Enchantment|"
  + "Hex Eater Vortex|Mirror of Disenchantment|Simple Thievery|"
  + "Animate Shambling Horror|Order of Undeath|Putrid Flesh|Feast for the Dead|"
  + "Jagged Bones|Contagion|Bloodletting|Ulcerous Lungs|Pain of Disenchantment|"
  + "Mark of Fury|Recurring Scourge|Corrupt Enchantment|Signet of Sorrow|"
  + "Signet of Suffering|Signet of Lost Souls|Well of Darkness|Blinding Surge|"
  + "Chilling Winds|Lightning Bolt|Storm Djinns Haste|Stone Striker|Sandstorm|"
  + "Stone Sheath|Ebon Hawk|Stoneflesh Aura|Glyph of Restoration|Ether Prism|"
  + "Master of Magic|Glowing Gaze|Savannah Heat|Flame Djinns Haste|Freezing Gust|"
  + "Rocky Ground|Sulfurous Haze|Siege Attack3|Sentry Trap skill|Caltrops monster|"
  + "Sacred Branch|Light of Seborhin|Judges Intervention|Supportive Spirit|"
  + "Watchful Healing|Healers Boon|Healers Covenant|Balthazars Pendulum|"
  + "Words of Comfort|Light of Deliverance|Scourge Enchantment|"
  + "Shield of Absorption|Reversal of Damage|Mending Touch|Critical Chop|"
  + "Agonizing Chop|Flail|Charging Strike|Headbutt|Lions Comfort|"
  + "Rage of the Ntouka|Mokele Smash|Overbearing Smash|Signet of Stamina|"
  + "Youre All Alone|Burst of Aggression|Enraging Charge|Crippling Slash|"
  + "Barbarous Slice|Vial of Purified Water|Disarm Trap|Feeding Frenzy skill|"
  + "Quake Of Ahdashim|Shield of Madness|Create Light of Seborhin|Unlock Cell|"
  + "Stop Pump||Shield of Madness1|Shield of Ether|Shield of Iron|"
  + "Shield of Strength|Wave of Torment|||Corsairs Net|Corrupted Healing|"
  + "Corrupted Roots|Corrupted Strength|Desert Wurm disguise|Junundu Feast|"
  + "Junundu Strike|Junundu Smash|Junundu Siege|Junundu Tunnel|Leave Junundu|"
  + "Summon Torment|Signal Flare|The Elixir of Strength|Ehzah from Above||"
  + "Last Rites of Torment|Abaddons Conspiracy|Hungers Bite|From Hell|"
  + "Pains Embrace|Call to the Torment|Command of Torment|Abaddons Favor|"
  + "Abaddons Chosen|Enchantment Collapse|Call of Sacrifice|Enemies Must Die|"
  + "Earth Vortex|Frost Vortex|Rough Current|Turbulent Flow|Prepared Shot|"
  + "Burning Arrow|Arcing Shot|Strike as One|Crossfire|Barbed Arrows|"
  + "Scavengers Focus|Toxicity|Quicksand|Storms Embrace|Trappers Speed|Tripwire|"
  + "Kournan Guardsman|Renewing Surge|Offering of Spirit|Spirits Gift|"
  + "Death Pact Signet|Reclaim Essence|Banishing Strike|Mystic Sweep|"
  + "Eremites Attack|Reap Impurities|Twin Moon Sweep|Victorious Sweep|"
  + "Irresistible Sweep|Pious Assault|Mystic Twister|Wind Prayers skill|"
  + "Grenths Fingers|Boon of the Gods|Aura of Thorns|Balthazars Rage|Dust Cloak|"
  + "Staggering Force|Pious Renewal|Mirage Cloak|Balthazars Rage|Arcane Zeal|"
  + "Mystic Vigor|Watchful Intervention|Vow of Piety|Vital Boon|"
  + "Heart of Holy Flame|Extend Enchantments|Faithful Intervention|Sand Shards|"
  + "Intimidating Aura beta version|Lyssas Haste|Guiding Hands|Fleeting Stability|"
  + "Armor of Sanctity|Mystic Regeneration|Vow of Silence|Avatar of Balthazar|"
  + "Avatar of Dwayna|Avatar of Grenth|Avatar of Lyssa|Avatar of Melandru|"
  + "Meditation|Eremites Zeal|Natural Healing|Imbue Health|Mystic Healing|"
  + "Dwaynas Touch|Pious Restoration|Signet of Pious Light|Intimidating Aura|"
  + "Mystic Sandstorm|Winds of Disenchantment|Rending Touch|Crippling Sweep|"
  + "Wounding Strike|Wearying Strike|Lyssas Assault|Chilling Victory|Conviction|"
  + "Enchanted Haste|Pious Concentration|Pious Haste|Whirling Charge|"
  + "Test of Faith|Blazing Spear|Mighty Throw|Cruel Spear|Harriers Toss|"
  + "Unblockable Throw|Spear of Lightning|Wearying Spear|Anthem of Fury|"
  + "Crippling Anthem|Defensive Anthem|Godspeed|Anthem of Flame|Go for the Eyes|"
  + "Anthem of Envy|Song of Power|Zealous Anthem|Aria of Zeal|Lyric of Zeal|"
  + "Ballad of Restoration|Chorus of Restoration|Aria of Restoration|"
  + "Song of Concentration|Anthem of Guidance|Energizing Chorus|"
  + "Song of Purification|Hexbreaker Aria|Brace Yourself|Awe|Enduring Harmony|"
  + "Blazing Finale|Burning Refrain|Finale of Restoration|Mending Refrain|"
  + "Purifying Finale|Bladeturn Refrain|Glowing Signet|Leadership skill|"
  + "Leaders Zeal|Leaders Comfort|Signet of Synergy|Angelic Protection|"
  + "Angelic Bond|Cautery Signet|Stand Your Ground|Lead the Way|Make Haste|"
  + "We Shall Return|Never Give Up|Help Me|Fall Back|Incoming|Theyre on Fire|"
  + "Never Surrender|Its Just a Flesh Wound|Barbed Spear|Vicious Attack|"
  + "Stunning Strike|Merciless Spear|Disrupting Throw|Wild Throw|"
  + "Curse of the Staff of the Mists|Aura of the Staff of the Mists|"
  + "Power of the Staff of the Mists|Scepter of Ether|Summoning of the Scepter|"
  + "Rise From Your Grave|Sugar Rush long|Corsair disguise|Queen Wail|Queen Armor|"
  + "Queen Heal|Queen Wail|Queen Armor|Queen Bite|Queen Thump|Queen Siege|"
  + "Junundu Tunnel monster skill|Skin of Stone|Dervish of the Mystic|"
  + "Dervish of the Wind|Paragon of Leadership|Paragon of Motivation|"
  + "Dervish of the Blade|Paragon of Command|Paragon of the Spear|"
  + "Dervish of the Earth|Master of DPS|Malicious Strike|Shattering Assault|"
  + "Golden Skull Strike|Black Spider Strike|Golden Fox Strike|Deadly Haste|"
  + "Assassins Remedy|Foxs Promise|Feigned Neutrality|Hidden Caltrops|"
  + "Assault Enchantments|Wastrels Collapse|Lift Enchantment|Augury of Death|"
  + "Signet of Toxic Shock|Signet of Twilight|Way of the Assassin|Shadow Walk|"
  + "Deaths Retreat|Shadow Prison|Swap|Shadow Meld|Price of Pride|"
  + "Air of Disenchantment|Signet of Clumsiness|Symbolic Posture|Toxic Chill|"
  + "Well of Silence|Glowstone|Mind Blast|Elemental Flame|Invoke Lightning|"
  + "Battle Cry1|Mending Shrine Bonus|Energy Shrine Bonus|"
  + "Northern Health Shrine Bonus|Southern Health Shrine Bonus|"
  + "Siege Attack Bombardment|Curse of Silence|To the Pain Hero Battles|"
  + "Edge of Reason|Depths of Madness environment effect|Cower in Fear|"
  + "Dreadful Pain|Veiled Nightmare|Base Protection|Kournan Siege Flame|"
  + "Drake Skin|Skale Vigor|Pahnai Salad item effect|Pensive Guardian|"
  + "Scribes Insight|Holy Haste|Glimmer of Light|Zealous Benediction|"
  + "Defenders Zeal|Signet of Mystic Wrath|Signet of Removal|Dismiss Condition|"
  + "Divert Hexes|Counterattack|Magehunter Strike|Soldiers Strike|Decapitate|"
  + "Magehunters Smash|Soldiers Stance|Soldiers Defense|Frenzied Defense|"
  + "Steady Stance|Steelfang Slash|Sunspear Battle Call|Untouchable|"
  + "Earth Shattering Blow|Corrupt Power|Words of Madness Qwytzylkak|"
  + "Gaze of Moavu Kaal|Presence of the Skale Lord|Madness Dart|"
  + "The Apocrypha is changing to another form||||Reform Carvings||Sunspear Siege|"
  + "Soul Torture|Screaming Shot|Keen Arrow|Rampage as One|Forked Arrow|"
  + "Disrupting Accuracy|Experts Dexterity|Roaring Winds|Magebane Shot|"
  + "Natural Stride|Hekets Rampage|Smoke Trap|Infuriating Heat|Vocal Was Sogolon|"
  + "Destructive Was Glaive|Wielders Strike|Gaze of Fury|Gaze of Fury attack|"
  + "Spirits Strength|Wielders Zeal|Sight Beyond Sight|Renewing Memories|"
  + "Wielders Remedy|Ghostmirror Light|Signet of Ghostly Might|Signet of Binding|"
  + "Caretakers Charge|Anguish|Anguish attack|Empowerment|Recovery|Weapon of Fury|"
  + "Xinraes Weapon|Warmongers Weapon|Weapon of Remedy|Rending Sweep|Onslaught|"
  + "Mystic Corruption|Grenths Grasp|Veil of Thorns|Harriers Grasp|"
  + "Vow of Strength|Ebon Dust Aura|Zealous Vow|Heart of Fury|Zealous Renewal|"
  + "Attackers Insight|Rending Aura|Featherfoot Grace|Reapers Sweep|"
  + "Harriers Haste|Focused Anger|Natural Temper|Song of Restoration|"
  + "Lyric of Purification|Soldiers Fury|Aggressive Refrain|Energizing Finale|"
  + "Signet of Aggression|Remedy Signet|Signet of Return|Make Your Time|"
  + "Cant Touch This|Find Their Weakness|The Power Is Yours|Slayers Spear|"
  + "Swift Javelin|Natures Speed|Weapon of Mastery|Accelerated Growth|"
  + "Forge the Way|Anthem of Aggression|Skale Hunt|Mandragor Hunt|Skree Battle|"
  + "Insect Hunt|Corsair Bounty|Plant Hunt|Undead Hunt|Eternal Suffering|"
  + "Eternal Suffering1|Eternal Suffering2|Eternal Languor|Eternal Languor1|"
  + "Eternal Languor2|Eternal Lethargy|Eternal Lethargy1|Eternal Lethargy2|||"
  + "Thirst of the Drought|Thirst of the Drought1|Thirst of the Drought2|"
  + "Thirst of the Drought3|Thirst of the Drought4|Lightbringer|"
  + "Lightbringers Gaze|Lightbringer Signet|Sunspear Rebirth Signet|Wisdom|"
  + "Maddened Strike|Maddened Stance|Spirit Form Remains of Sahlahja|"
  + "Gods Blessing|Monster Hunt|Monster Hunt1|Monster Hunt2|Monster Hunt3|"
  + "Elemental Hunt|Elemental Hunt1|Skree Battle1|Insect Hunt1|Insect Hunt2|"
  + "Demon Hunt|Minotaur Hunt|Plant Hunt1|Plant Hunt2|Skale Hunt1|Skale Hunt2|"
  + "Heket Hunt|Heket Hunt1|Kournan Bounty|Mandragor Hunt1|Mandragor Hunt2|"
  + "Corsair Bounty1|Kournan Bounty1|Dhuum Battle|Menzies Battle|Elemental Hunt2|"
  + "Monolith Hunt|Monolith Hunt1|Margonite Battle|Monster Hunt4|Titan Hunt|"
  + "Mandragor Hunt3|Giant Hunt|Undead Hunt1|Kournan Siege|Lose your Head|"
  + "Wandering Mind||Altar Buff|Sugar Rush short|Choking Breath|Junundu Bite|"
  + "Blinding Breath|Burning Breath|Junundu Wail|Capture Point|"
  + "Approaching the Vortex||||Avatar of Sweetness||Corrupted Lands||"
  + "Words of Madness|Unknown Junundu Ability||||"
  + "Torment Slash Smothering Tendrils|Bonds of Torment|Shadow Smash|"
  + "Bonds of Torment effect|Consume Torment|Banish Enchantment|Summoning Shadows|"
  + "Lightbringers Insight||Repressive Energy|Enduring Torment|Shroud of Darkness|"
  + "Demonic Miasma|Enraged|Touch of Aaaaarrrrrrggghhh|Wild Smash|"
  + "Unyielding Anguish|Jadoths Storm of Judgment|Anguish Hunt|"
  + "Avatar of Holiday Cheer|Side Step|Jack Frost|"
  + "Avatar of Grenth snow fighting skill|Avatar of Dwayna snow fighting skill|"
  + "Steady Aim|Rudis Red Nose|||||Charm Animal White Mantle|"
  + "Volatile Charr Crystal|Hard mode|Claim Resource Heroes Ascent|Hard mode1|"
  + "Hard Mode NPC Buff|Sugar Jolt short|Rollerbeetle Racer|Ram|Harden Shell|"
  + "Rollerbeetle Dash|Super Rollerbeetle|Rollerbeetle Echo|Distracting Lunge|"
  + "Rollerbeetle Blast|Spit Rocks|Lunar Blessing|Lucky Aura|Spiritual Possession|"
  + "Water|Pig Form|Beetle Metamorphosis||Sugar Jolt long|Golden Egg skill|"
  + "Torturous Embers|Test Buff|Infernal Rage|Putrid Flames|Shroud of Ash|"
  + "Flame Call|Torturers Inferno|Whirling Fires|"
  + "Charr Siege Attack What Must Be Done|Charr Siege Attack Against the Charr|"
  + "Birthday Cupcake skill||Blessing of the Luxons|Shadow Sanctuary luxon|"
  + "Ether Nightmare luxon|Signet of Corruption luxon|Elemental Lord luxon|"
  + "Selfless Spirit luxon|Triple Shot luxon|Save Yourselves luxon|"
  + "Aura of Holy Might luxon||Spear of Fury luxon|Attribute Balance|"
  + "Monster Hunt5|Monster Hunt6|Mandragor Hunt4|Mandragor Hunt5|Giant Hunt1|"
  + "Giant Hunt2|Skree Battle2|Skree Battle3|Insect Hunt3|Insect Hunt4|"
  + "Minotaur Hunt1|Minotaur Hunt2|Corsair Bounty2|Corsair Bounty3|Plant Hunt3|"
  + "Plant Hunt4|Skale Hunt3|Skale Hunt4|Heket Hunt2|Heket Hunt3|Kournan Bounty2|"
  + "Kournan Bounty3|Undead Hunt2|Undead Hunt3|Fire Dart|Ice Dart|Poison Dart|"
  + "Vampiric Assault|Lotus Strike|Golden Fang Strike|Way of the Mantis|"
  + "Falling Lotus Strike|Sadists Signet|Signet of Distraction|Signet of Recall|"
  + "Power Lock|Waste Not Want Not|Sum of All Fears|Withering Aura|Cacophony|"
  + "Winters Embrace|Earthen Shackles|Ward of Weakness|Glyph of Swiftness|"
  + "Cure Hex|Smite Condition|Smiters Boon|Castigation Signet|Purifying Veil|"
  + "Pulverizing Smash|Keen Chop|Knee Cutter|Grapple|Radiant Scythe|Grenths Aura|"
  + "Signet of Pious Restraint|Farmers Scythe|Energetic Was Lee Sa|"
  + "Anthem of Weariness|Anthem of Disruption|Burning Ground|Freezing Ground|"
  + "Poison Ground|Fire Jet|Ice Jet|Poison Jet|Lava Pool|Water Pool|Fire Spout|"
  + "Ice Spout|Poison Spout|Dhuum Battle1|Dhuum Battle2|Elemental Hunt3|"
  + "Elemental Hunt4|Monolith Hunt2|Monolith Hunt3|Margonite Battle1|"
  + "Margonite Battle2|Menzies Battle1|Menzies Battle2|Anguish Hunt1|Titan Hunt1|"
  + "Titan Hunt2|Monster Hunt7|Monster Hunt8|Sarcophagus Spores|Exploding Barrel|"
  + "Greater Hard Mode NPC Buff|Fire Boulder|Dire Snowball|Boulder|"
  + "Summon Spirits luxon|Shadow Fang|Calculated Risk|Shrinking Armor|Aneurysm|"
  + "Wandering Eye|Foul Feast|Putrid Bile|Shell Shock|Glyph of Immolation|"
  + "Patient Spirit|Healing Ribbon|Aura of Stability|Spotless Mind|Spotless Soul|"
  + "Disarm|I Meant to Do That|Rapid Fire|Sloth Hunters Shot|Aura Slicer|"
  + "Zealous Sweep|Pure Was Li Ming|Weapon of Aggression|Chest Thumper|"
  + "Hasty Refrain|Drain Minion|Cracked Armor|Berserk|Fleshreavers Escape|Chomp|"
  + "Twisting Jaws|Burning Immunity|Mandragors Charge|Rock Slide|Avalanche effect|"
  + "Snaring Web|Ceiling Collapse|Trample|Wurm Bile|Ground Cover|"
  + "Shadow Sanctuary kurzick|Ether Nightmare kurzick|"
  + "Signet of Corruption kurzick|Elemental Lord kurzick|Selfless Spirit kurzick|"
  + "Triple Shot kurzick|Save Yourselves kurzick|Aura of Holy Might kurzick|"
  + "Spear of Fury kurzick|Summon Spirits kurzick|Critical Agility|Cry of Pain|"
  + "Necrosis|Intensity|Seed of Life|Call of the Eye|Whirlwind Attack|"
  + "Never Rampage Alone|Eternal Aura|Vampirism|Vampirism attack|"
  + "Theres Nothing to Fear|Ursan Rage Blood Washes Blood|"
  + "Ursan Strike Blood Washes Blood||Sneak Attack|Firebomb Explosion|Firebomb|"
  + "Shield of Fire|Respawn|Marked For Death|Spirit World Retreat|Long Claws|"
  + "Shattered Spirit|Spirit Roar|Spirit Senses|Unseen Aggression|"
  + "Volfen Pounce Curse of the Nornbear|Volfen Claw Curse of the Nornbear||"
  + "Volfen Bloodlust Curse of the Nornbear|Volfen Agility Curse of the Nornbear|"
  + "Volfen Blessing Curse of the Nornbear|Charging Spirit|Trampling Ox|"
  + "Smoke Powder Defense|Confusing Images|Hexers Vigor|Masochism|Piercing Trap|"
  + "Companionship|Feral Aggression|Disrupting Shot|Volley|Expert Focus|"
  + "Pious Fury|Crippling Victory|Sundering Weapon|Weapon of Renewal|"
  + "Maiming Spear|Temporal Sheen|Flux Overload|A pool of water|"
  + "Phase Shield effect|Phase Shield monster skill|Vitality Transfer|"
  + "Golem Strike|Bloodstone Slash|Energy Blast golem|Chaotic Energy|"
  + "Golem Fire Shield|The Way of Duty|The Way of Kinship|"
  + "Diamondshard Mist environment effect|Diamondshard Grave|The Way of Strength|"
  + "Diamondshard Mist|Raven Blessing A Gate Too Far||Raven Flight A Gate Too Far|"
  + "Raven Shriek A Gate Too Far|Raven Swoop A Gate Too Far|"
  + "Raven Talons A Gate Too Far|Aspect of Oak|Long Claws1|Tremor|"
  + "Rage of the Jotun|Thundering Roar|Sundering Soulcrush|Pyroclastic Shot|"
  + "Explosive Force|||Rolling Shift|Powder Keg Explosion|"
  + "Signet of Deadly Corruption|Way of the Master|Defile Defenses|"
  + "Angorodons Gaze|Magnetic Surge|Slippery Ground|Glowing Ice|Energy Blast|"
  + "Distracting Strike|Symbolic Strike|Soldiers Speed|Body Blow|Body Shot|"
  + "Poison Tip Signet|Signet of Mystic Speed|Shield of Force|Mending Grip|"
  + "Spiritleech Aura|Rejuvenation|Agony|Ghostly Weapon|Inspirational Speech|"
  + "Burning Shield|Holy Spear|Spear Swipe|Alkars Alchemical Acid|"
  + "Light of Deldrimor|Ear Bite|Low Blow|Brawling Headbutt|Dont Trip|"
  + "By Urals Hammer|Drunken Master|Great Dwarf Weapon|Great Dwarf Armor|"
  + "Breath of the Great Dwarf|Snow Storm|Black Powder Mine|Summon Mursaat|"
  + "Summon Ruby Djinn|Summon Ice Imp|Summon Naga Shaman|Deft Strike|"
  + "Signet of Infection|Tryptophan Signet|Ebon Battle Standard of Courage|"
  + "Ebon Battle Standard of Wisdom|Ebon Battle Standard of Honor|"
  + "Ebon Vanguard Sniper Support|Ebon Vanguard Assassin Support|Well of Ruin|"
  + "Atrophy|Spear of Redemption||Gelatinous Material Explosion|"
  + "Gelatinous Corpse Consumption|Gelatinous Mutation|Gelatinous Absorption|"
  + "Unstable Ooze Explosion|Golem Shrapnel|Unstable Aura|Unstable Pulse|"
  + "Polymock Power Drain|Polymock Block|Polymock Glyph of Concentration|"
  + "Polymock Ether Signet|Polymock Glyph of Power|Polymock Overload|"
  + "Polymock Glyph Destabilization|Polymock Mind Wreck|Order of Unholy Vigor|"
  + "Order of the Lich|Master of Necromancy|Animate Undead|Polymock Deathly Chill|"
  + "Polymock Rising Bile|Polymock Rotting Flesh|Polymock Lightning Strike|"
  + "Polymock Lightning Orb|Polymock Lightning Djinns Haste|Polymock Flare|"
  + "Polymock Immolate|Polymock Meteor|Polymock Ice Spear|Polymock Icy Prison|"
  + "Polymock Mind Freeze|Polymock Ice Shard Storm|Polymock Frozen Trident|"
  + "Polymock Smite|Polymock Smite Hex|Polymock Bane Signet|"
  + "Polymock Stone Daggers|Polymock Obsidian Flame|Polymock Earthquake|"
  + "Polymock Frozen Armor|Polymock Glyph Freeze|Polymock Fireball|"
  + "Polymock Rodgorts Invocation|Polymock Calculated Risk|"
  + "Polymock Recurring Insecurity|Polymock Backfire|Polymock Guilt|"
  + "Polymock Lamentation|Polymock Spirit Rift|Polymock Painful Bond|"
  + "Polymock Signet of Clumsiness|Polymock Migraine|Polymock Glowing Gaze|"
  + "Polymock Searing Flames|Polymock Signet of Revenge|"
  + "Polymock Signet of Smiting|Polymock Stoning|Polymock Eruption|"
  + "Polymock Shock Arrow|Polymock Mind Shock|Polymock Piercing Light Spear|"
  + "Polymock Mind Blast|Polymock Savannah Heat|Polymock Diversion|"
  + "Polymock Lightning Blast|Polymock Poisoned Ground|Polymock Icy Bonds|"
  + "Polymock Sandstorm|Polymock Banish|Mergoyle Form|Skale Form|Gargoyle Form|"
  + "Ice Imp Form|Fire Imp Form|Kappa Form|Aloe Seed Form|Earth Elemental Form|"
  + "Fire Elemental Form|Ice Elemental Form|Mirage Iboga Form|Wind Rider Form|"
  + "Naga Shaman Form|Mantis Dreamweaver Form|Ruby Djinn Form|Gaki Form|"
  + "Stone Rain Form|Mursaat Elementalist Form|Crystal Shield|Crystal Snare|"
  + "Paranoid Indignation|Searing Breath|Kraks Charge|Brawling|Brawling Block|"
  + "Brawling Jab|Brawling Jab1|Brawling Straight Right|Brawling Hook|"
  + "Brawling Hook1|Brawling Uppercut|Brawling Combo Punch|"
  + "Brawling Headbutt Brawling skill|STAND UP|Call of Destruction|Flame Jet|"
  + "Lava Ground|Lava Wave||Spirit Shield|Summoning Lord|"
  + "Charm Animal Ashlyn Spiderfriend|"
  + "Charr Siege Attack Assault on the Stronghold|Finish Him|Dodge This|"
  + "I Am the Strongest|I Am Unstoppable|A Touch of Guile|You Move Like a Dwarf|"
  + "You Are All Weaklings|Feel No Pain|Club of a Thousand Bears||Talon Strike|"
  + "Lava Blast|Thunderfist Strike||Alkars Concoction|Murakais Consumption|"
  + "Murakais Censure|Murakais Calamity|Murakais Storm of Souls|Edification|"
  + "Heart of the Norn|Ursan Blessing|Ursan Strike|Ursan Rage|Ursan Roar|"
  + "Ursan Force|Volfen Blessing|Volfen Claw|Volfen Pounce|Volfen Bloodlust|"
  + "Volfen Agility|Raven Blessing|Raven Talons|Raven Swoop|Raven Shriek|"
  + "Raven Flight|Totem of Man|Filthy Explosion|Murakais Call|Spawn Pods|"
  + "Enraged Blast|Spawn Hatchling|Ursan Roar Blood Washes Blood|"
  + "Ursan Force Blood Washes Blood|Ursan Aura|Consume Flames|"
  + "Aura of the Great Destroyer|Destroy the Humans|Charr Flame Keeper Form|"
  + "Titan Form|Skeletal Mage Form|Smoke Wraith Form|Bone Dragon Form||"
  + "Dwarven Arcanist Form|Dolyak Rider Form|Extract Inscription|"
  + "Charr Shaman Form|Mindbender|Smooth Criminal|Technobabble|Radiation Field|"
  + "Asuran Scan|Air of Superiority|Mental Block|Pain Inverter|Healing Salve|"
  + "Ebon Escape|Weakness Trap|Winds|Dwarven Stability|Stout Hearted|"
  + "Inscribed Ettin Aura|Decipher Inscriptions|Rebel Yell||Asuran Flame Staff|"
  + "Aura of the Bloodstone|Aura of the Bloodstone1|Aura of the Bloodstone2|"
  + "Haunted Ground|Asuran Bodyguard Rank2|Asuran Bodyguard Rank3|"
  + "Asuran Bodyguard Rank4|Energy Channel|Hunt Rampage||Boss Bounty|"
  + "Hunt Point Bonus|Hunt Point Bonus1|Hunt Point Bonus2|Time Attack|"
  + "Dwarven Raider|Dwarven Raider Rank2|Dwarven Raider Rank3|"
  + "Dwarven Raider Rank4|Great Dwarfs Blessing|Hunt Rampage1||Boss Bounty1|"
  + "Hunt Point Bonus3|Hunt Point Bonus4||Time Attack1|Vanguard Patrol|"
  + "Vanguard Patrol Rank2|Vanguard Patrol Rank3|Vanguard Patrol Rank4|"
  + "Vanguard Commendation|Hunt Rampage2||Boss Bounty2|||||Norn Hunting Party|"
  + "Norn Hunting Party Rank2|Norn Hunting Party Rank3|Norn Hunting Party Rank4|"
  + "Strength of the Norn|Hunt Rampage3|||||||Asuran Bodyguard|Desperate Howl|"
  + "Gloat|Metamorphosis|Inner Fire|Elemental Shift|Dryders Feast|"
  + "Fungal Explosion|Blood Rage|Parasitic Bite|False Death|Ooze Combination|"
  + "Ooze Division|Bear Form|Sweeping Strikes|Spore Explosion|Dormant Husk|"
  + "Monkey See Monkey Do|Feeding Frenzy|Tengus Mimicry|Tongue Lash|"
  + "Soulrending Shriek|Unreliable|Siege Devourer|Siege Devourer Feast|"
  + "Devourer Bite|Siege Devourer Swipe|Devourer Siege|HYAHHHHH|HYAHHHHH1|"
  + "HYAHHHHH2|HYAHHHHH3|Dismount Siege Devourer|The Masters Mark|"
  + "The Snipers Spear|Mount|Reverse Polarity Fire Shield|Tengus Gaze|"
  + "Fix Monster Attributes|Armor of Salvation item effect|"
  + "Grail of Might item effect|Essence of Celerity item effect|"
  + "Stone Dwarf Transformation|Forgewights Blessing|Selvetarms Blessing|"
  + "Thommiss Blessing|Duncans Defense||Rands Attack|Selvetarms Attack|"
  + "Thommiss Attack|Create Spore||||Invigorating Mist|Courageous Was Saidra|"
  + "Animate Undead Palawa Joko|Order of Unholy Vigor Palawa Joko|"
  + "Order of the Lich Palawa Joko|Golem Boosters|Charm Animal monster1|"
  + "Wurm Siege Eye of the North|Tongue Whip|Lit Torch|Dishonorable|"
  + "Hard Mode Dungeon Boss|Veteran Asuran Bodyguard|Veteran Dwarven Raider|"
  + "Veteran Vanguard Patrol|Veteran Norn Hunting Party||||||||||||||"
  + "Dwarven Raider4|Dwarven Raider5|Dwarven Raider6|Dwarven Raider7||"
  + "Great Dwarfs Blessing1|Boss Bounty3|||Hunt Point Bonus5|Hunt Point Bonus6|"
  + "Hunt Rampage4|Time Attack2|Vanguard Patrol4|||||Boss Bounty4||"
  + "Hunt Point Bonus7||||Vanguard Commendation1||Norn Hunting Party4|"
  + "Norn Hunting Party5|Norn Hunting Party6|Norn Hunting Party7||Boss Bounty5||"
  + "Strength of the Norn1|Hunt Point Bonus8||Hunt Point Bonus9|Hunt Rampage5|"
  + "Time Attack3|Candy Corn skill|Candy Apple skill|Anton Costume Brawl disguise|"
  + "Erys Vasburg Costume Brawl disguise|Olias Costume Brawl disguise|"
  + "Argo Costume Brawl disguise|Mhenlo Costume Brawl disguise|"
  + "Lukas Costume Brawl disguise|Aidan Costume Brawl disguise|"
  + "Kahmu Costume Brawl disguise|Razah Costume Brawl disguise|"
  + "Morgahn Costume Brawl disguise|Nika Costume Brawl disguise|"
  + "Seaguard Hala Costume Brawl disguise|Livia Costume Brawl disguise|"
  + "Cynn Costume Brawl disguise|Tahlkora Costume Brawl disguise|"
  + "Devona Costume Brawl disguise|Zho Costume Brawl disguise|"
  + "Melonni Costume Brawl disguise|Xandra Costume Brawl disguise|"
  + "Hayda Costume Brawl disguise|Complicate|Reapers Mark|Enfeeble|"
  + "Desecrate Enchantments|Signet of Lost Souls|Insidious Parasite|"
  + "Searing Flames|Glowing Gaze|Steam|Flame Djinns Haste|Liquid Flame|"
  + "Blessed Light|Shield of Absorption|Smite Condition|Crippling Slash|"
  + "Sun and Moon Slash|Enraging Charge|Tiger Stance|Burning Arrow|Natural Stride|"
  + "Falling Lotus Strike|Anthem of Weariness|Pious Fury|Pie Induced Ecstasy|"
  + "Charm Animal Charr Demolisher|Togo disguise|Turai Ossa disguise|"
  + "Gwen disguise|Saul DAlessio disguise|Dragon Empire Rage|"
  + "Call to the Spirit Realm|Call of Haste Pv P|Hide|Feign Death|Flee|Throw Rock|"
  + "Nightmarish Aura|Siege Strike|Spike Trap spell|Barbed Bomb|"
  + "Fire and Brimstone|Balm Bomb|Explosives|Rations|Form Up and Advance|Advance|"
  + "Spectral Agony Saul DAlessio|Stun Bomb|Banner of the Unseen|"
  + "Signet of the Unseen|For Elona|Giant Stomp Turai Ossa|"
  + "Whirlwind Attack Turai Ossa|Junundu Siege1|Distortion Gwen|"
  + "Shared Burden Gwen|Sum of All Fears Gwen|Castigation Signet Saul DAlessio|"
  + "Unnatural Signet Saul DAlessio|Dragon Slash Turai Ossa|Essence Strike Togo|"
  + "Spirit Burn Togo|Spirit Rift Togo|Mend Body and Soul Togo|"
  + "Offering of Spirit Togo|Disenchantment Togo|Fire Dart1||||||"
  + "Corrupted Haiju Lagoon Water|Journey to the North||Rat Form|Ox Form|"
  + "Tiger Form|Rabbit Form|Dragon Form|Snake Form|Horse Form|Sheep Form|"
  + "Monkey Form|Rooster Form|Dog Form|Party Time|Victory is Ours|"
  + "Dark Soul Explosion|Chaotic Soul Explosion|Fiery Soul Explosion|"
  + "Rejuvenating Soul Explosion|Plague Spring|Unbalancing Soul Explosion|"
  + "Shadowy Soul Explosion|Ethereal Soul Explosion|Redemption of Purity|"
  + "Purify Energy|Purifying Flame|Purifying Prayer|Strength of Purity|"
  + "Spring of Purity|Way of the Pure|Purify Soul|Aura of Purity|Anthem of Purity|"
  + "Falkens Fire Fist|Falken Quick|Mind Wrack Pv P|Quickening Terrain|"
  + "Massive Damage|Minion Apocalypse||Combat Costume Assassin|"
  + "Combat Costume Mesmer|Combat Costume Necromancer|Combat Costume Elementalist|"
  + "Combat Costume Monk|Combat Costume Warrior|Combat Costume Ranger|"
  + "Combat Costume Dervish|Combat Costume Ritualist|Combat Costume Paragon|||||||"
  + "Jade Brotherhood Bomb|Mad Kings Fan||Candy Corn Strike|"
  + "Rocket Propelled Gobstopper|Rain of Terror spell|Cry of Madness|"
  + "Sugar Infusion|Feast of Vengeance|Animate Candy Minions|Taste of Undeath|"
  + "Scourge of Candy|Motivating Insults|Mad King Pony Support|"
  + "Its Good to Be King|Maddening Laughter|Mad Kings Influence|||||||||||||||||||"
  + "Hidden Talent|Couriers Haste|Xinraes Revenge||||||||||||||||"
  + "Meek Shall Inherit|||Inverse Ninja Law||||||||||||||||||||||||||Abyssal Form|"
  + "Asura Form|Awakened Head Form|Spider Form|Charr Form|Golem Form|"
  + "Hellhound Form|Norn Form|Ooze Form|Rift Warden Form||Yeti Form|Snowman Form|"
  + "Energy Drain Pv P|Energy Tap Pv P|Pv P effect|Ward Against Melee Pv P|"
  + "Lightning Orb Pv P|Aegis Pv P|Watch Yourself Pv P|Enfeeble Pv P|"
  + "Ether Renewal Pv P|Penetrating Attack Pv P|Shadow Form Pv P|Discord Pv P|"
  + "Sundering Attack Pv P|Ritual Lord Pv P|Flesh of My Flesh Pv P|"
  + "Ancestors Rage Pv P|Splinter Weapon Pv P|Assassins Remedy Pv P|"
  + "Blinding Surge Pv P|Light of Deliverance Pv P|Death Pact Signet Pv P|"
  + "Mystic Sweep Pv P|Eremites Attack Pv P|Harriers Toss Pv P|"
  + "Defensive Anthem Pv P|Ballad of Restoration Pv P|Song of Restoration Pv P|"
  + "Incoming Pv P|Never Surrender Pv P||Mantra of Inscriptions Pv P|"
  + "For Great Justice Pv P|Mystic Regeneration Pv P|Enfeebling Blood Pv P|"
  + "Summoning Sickness|Signet of Judgment Pv P|Chilling Victory Pv P|||"
  + "Unyielding Aura Pv P|Spirit Bond Pv P|Weapon of Warding Pv P|Bamph Lite|"
  + "Smiters Boon Pv P|Battle Fervor Deactivating ROX|"
  + "Cloak of Faith Deactivating ROX|Dark Aura Deactivating ROX|"
  + "Chaotic Power Deactivating ROX|Strength of the Oak Deactivating ROX|"
  + "Sinister Golem Form|Reactor Blast|Reactor Blast Timer|"
  + "Jade Brotherhood Disguise|Internal Power Engaged|Target Acquisition|NOX Beam|"
  + "NOX Field Dash|NOXion Buster|Countdown|Bit Golem Breaker|Bit Golem Rectifier|"
  + "Bit Golem Crash|Bit Golem Force||NOX Phantom|NOX Thunder|NOX Lock On|"
  + "NOX Driver|NOX Fire|NOX Knuckle|NOX Divider Drive|"
  + "Yo Ho Ho and a Bottle of Grog|Oath of Protection|Sloth Hunters Shot Pv P|"
  + "Bamph Lifesteal|Shrine Backlash|Amulet of Protection|Eviscerate|Rush|"
  + "Lions Comfort|Melandrus Shot|Sloth Hunters Shot|Reversal of Damage|"
  + "Empathic Removal|Castigation Signet|Wail of Doom|Rip Enchantment|Foul Feast|"
  + "Plague Sending|Overload|Wastrels Worry|Lyssas Aura|Empathy|Shatterstone|"
  + "Glowing Ice|Freezing Gust|Glyph of Immolation|Glyph of Restoration|"
  + "Hidden Caltrops|Black Spider Strike|Caretakers Charge|Signet of Mystic Speed|"
  + "Signet of Rage|Signet of Judgement|Vigorous Spirit|"
  + "Western Health Shrine Bonus|Eastern Health Shrine Bonus|"
  + "Experts Dexterity Pv P||Delayed Blast BAMPH|Grentch Form||Snowball1|"
  + "Signet of Spirits Pv P|Signet of Ghostly Might Pv P|Avatar of Grenth Pv P|"
  + "Oversized Tonic Warning|Read the Wind Pv P|Mursaat Form|Blue Rock Candy Rush|"
  + "Green Rock Candy Rush|Red Rock Candy Rush|Archer Form|"
  + "Avatar of Balthazar Form|Champion of Balthazar Form|Priest of Balthazar Form|"
  + "The Black Beast of Arrgh Form|Crystal Guardian Form|Crystal Spider Form|"
  + "Bone Dragon Form1|Saltspray Dragon Form|Eye of Janthir Form|Footman Form|"
  + "Ghostly Hero Form|Guild Lord Form|Gwen Doll Form|Black Moa Form|"
  + "Black Moa Chick Form|Moa Bird Form|White Moa Form|Rainbow Phoenix Form|"
  + "Brown Rabbit Form|White Rabbit Form|Seer Form|Swarm of Bees Form|"
  + "Seed of Resurrection1|Fragility Pv P|Strength of Honor Pv P|Gunthers Gaze||"
  + "Warriors Endurance Pv P|Armor of Unfeeling Pv P|Signet of Creation Pv P|"
  + "Union Pv P|Shadowsong Pv P|Pain Pv P|Destruction Pv P|Soothing Pv P|"
  + "Displacement Pv P|Preservation Pv P|Life Pv P|Recuperation Pv P|"
  + "Dissonance Pv P|Earthbind Pv P|Shelter Pv P|Disenchantment Pv P|"
  + "Restoration Pv P|Bloodsong Pv P|Wanderlust Pv P|Savannah Heat Pv P|"
  + "Gaze of Fury Pv P|Anguish Pv P|Empowerment Pv P|Recovery Pv P|"
  + "Go for the Eyes Pv P|Brace Yourself Pv P|Blazing Finale Pv P|"
  + "Bladeturn Refrain Pv P|Signet of Return Pv P|Cant Touch This Pv P|"
  + "Stand Your Ground Pv P|We Shall Return Pv P|Find Their Weakness Pv P|"
  + "Never Give Up Pv P|Help Me Pv P|Fall Back Pv P|Agony Pv P|Rejuvenation Pv P|"
  + "Anthem of Disruption Pv P|Shadowsong Master Riyo|Pain1|Wanderlust1|"
  + "Spirit Siphon Master Riyo|Comfort Animal Pv P||Melandrus Assault Pv P|"
  + "Shroud of Distress Pv P|Unseen Fury Pv P|Predatory Bond Pv P|"
  + "Enraged Lunge Pv P|Conviction Pv P|Signet of Deadly Corruption Pv P|"
  + "Masochism Pv P|Pain attack Togo|Pain attack Togo1|Pain attack Togo2|"
  + "Unholy Feast Pv P|Signet of Agony Pv P|Escape Pv P|Death Blossom Pv P|"
  + "Finale of Restoration Pv P|Mantra of Resolve Pv P|Lesser Hard Mode NPC Buff|"
  + "Charm Animal1|Charm Animal2|Henchman|Charm Animal Codex|"
  + "Agent of the Mad King|Sugar Rush Agent of the Mad King|Sticky Ground|"
  + "Sugar Shock|The Mad Kings Influence|Bone Spike|Flurry of Splinters|"
  + "Everlasting Mobstopper skill|Weakened by Dhuum|Curse of Dhuum|"
  + "Dhuums Rest Reaper skill|Dhuum skill|Summon Champion|Summon Minions|"
  + "Touch of Dhuum|Reaping of Dhuum|Judgment of Dhuum|Weight of Dhuum hex|"
  + "Dhuums Rest|Spiritual Healing|Encase Skeletal|Reversal of Death|Ghostly Fury|"
  + "Henchman Form Pudash|Henchman Form Dahlia|Henchman Form Disenmaedel|"
  + "Henchman Form Errol Hyl|Henchman Form Lulu Xan|Henchman Form Tannaros|"
  + "Henchman Form Cassie Santi|Henchman Form Redemptor Frohs|"
  + "Henchman Form Julyia|Henchman Form Bellicus|Henchman Form Dirk Shadowrise|"
  + "Henchman Form Vincent Evan|Henchman Form Luzy Fiera|Henchman Form Motoko Kai|"
  + "Henchman Form Hinata|Henchman Form Kah Xan|Henchman Form Narcissia|"
  + "Henchman Form Zen Siert|Henchman Form Blenkeh|"
  + "Henchman Form Aurora Allesandra|Henchman Form Teena the Raptor|"
  + "Henchman Form Lora Lanaya|Henchman Form Adepte|"
  + "Henchman Form Haldibarn Earendul|Henchman Form Daky|"
  + "Henchman Form Syn Spellstrike|Henchman Form Divinus Tutela|"
  + "Henchman Form Blahks|Henchman Form Erick|Henchman Form Ghavin|"
  + "Henchman Form Hobba Inaste|Henchman Form Bacchi Coi|Henchman Form Suzu|"
  + "Henchman Form Rollo Lowlo|Henchman Form Fuu Rin|Henchman Form Nuno|"
  + "Henchman Form Alsacien|Henchman Form Uto Wrotki|Henchman Form Khai Kemnebi|"
  + "Henchman Form Cole||Weight of Dhuum|Spirit Form disguise|"
  + "Spiritual Healing Reaper skill|Ghostly Fury Reaper skill|Reindeer Form|"
  + "Reindeer Form1|Reindeer Form2|Staggering Blow Pv P|Lightning Reflexes Pv P|"
  + "Fierce Blow Pv P|Renewing Smash Pv P|Heal as One Pv P|Glass Arrows Pv P|"
  + "Protective Was Kaolai Pv P|Keen Arrow Pv P|Anthem of Envy Pv P|"
  + "Mending Refrain Pv P|Lesser Flame Sentinel Resistance|Empathy Pv P|"
  + "Crippling Anguish Pv P|Pain attack Signet of Spirits|"
  + "Pain attack Signet of Spirits1|Pain attack Signet of Spirits2|"
  + "Soldiers Stance Pv P|Destructive Was Glaive Pv P||Charm Drake|||"
  + "Theres not enough time|Keirans Sniper Shot|Falken Punch|Golem Pilebunker|"
  + "Drunken Stumbling||||Koros Gaze|Ebon Vanguard Assassin Support NPC|"
  + "Ebon Vanguard Battle Standard of Power|Loose Magic|Well Supplied|"
  + "Guild Monument Protected|Strong Natural Resistance|Elite Regeneration|"
  + "Elite Regeneration1|Mantra of Signets Pv P|Shatter Delusions Pv P|"
  + "Illusionary Weaponry Pv P|Panic Pv P|Migraine Pv P|Accumulated Pain Pv P|"
  + "Psychic Instability Pv P|Shared Burden Pv P|Stolen Speed Pv P|"
  + "Unnatural Signet Pv P|Spiritual Pain Pv P|Frustration Pv P|Mistrust Pv P|"
  + "Enchanters Conundrum Pv P|Signet of Clumsiness Pv P|"
  + "Mirror of Disenchantment Pv P|Wandering Eye Pv P|Calculated Risk Pv P|"
  + "Adoration|Impending Dhuum|Sacrifice Pawn|Isaiahs Balance|"
  + "Toriimos Burning Fury|Oath of Protection1||Defy Pain Pv P|Entourage|"
  + "Spectral Infusion|Entourage Buffer|Wastrels Demise Pv P||"
  + "Shiro Tagachi Costume Brawl disguise|Dunham Costume Brawl disguise|"
  + "Palawa Joko Costume Brawl disguise|Lawrence Crafton Costume Brawl disguise|"
  + "Saul DAlessio Costume Brawl disguise|Turai Ossa Costume Brawl disguise|"
  + "Lieutenant Thackeray Costume Brawl disguise|Gehraz Costume Brawl disguise|"
  + "Master Togo Costume Brawl disguise|Egil Fireteller Costume Brawl disguise|"
  + "Mysterious Assassin Costume Brawl disguise|Gwen Costume Brawl disguise|"
  + "Eve Costume Brawl disguise|Elementalist Aziure Costume Brawl disguise|"
  + "Jamei Costume Brawl disguise|Jora Costume Brawl disguise|"
  + "Margrid the Sly Costume Brawl disguise|Varesh Ossa Costume Brawl disguise|"
  + "Headmaster Quin Costume Brawl disguise|Kormir Costume Brawl disguise||"
  + "Barbed Signet Pv P|Heal Party Pv P|Spoil Victor Pv P|Visions of Regret Pv P|"
  + "Keirans Sniper Shot Hearts of the North|Gravestone Marker|Terminal Velocity|"
  + "Relentless Assault|Natures Blessing|Find Their Weakness Thackeray|"
  + "Theres Nothing to Fear Thackeray|Coming of Spring|Promise of Death|"
  + "Withering Blade|Deaths Embrace|Venom Fang|Survivors Will|"
  + "Keiran Thackeray disguise|Rain of Arrows||Fox Fangs Pv P|Wild Strike Pv P|"
  + "Ultra Snowball|Blizzard|||||Ultra Snowball1|Ultra Snowball2|Ultra Snowball3|"
  + "Ultra Snowball4|Banishing Strike Pv P|Twin Moon Sweep Pv P|"
  + "Irresistible Sweep Pv P|Pious Assault Pv P|Ebon Dust Aura Pv P|"
  + "Heart of Holy Flame Pv P|Guiding Hands Pv P|Avatar of Dwayna Pv P|"
  + "Avatar of Melandru Pv P|Mystic Healing Pv P|Signet of Pious Restraint Pv P|"
  + "Vanguard Initiate||||||||Victorious Renewal|A Dying Curse|||||"
  + "Rage of the Djinn|Fevered Dreams Pv P|Stun Grenade|Fragmentation Grenade|"
  + "Tear Gas|Land Mine|Riot Shield|Club Strike|Bludgeon|Tango Down|Ill Be Back|"
  + "Phased Plasma Burst|Plasma Shot|Annihilator Bash|Sky Net|Damage Assessment|"
  + "Going Commando||Koss Form|Dunkoro Form|Melonni Form|Acolyte Jin Form|"
  + "Acolyte Sousuke Form|Tahlkora Form|Zhed Shadowhoof Form|Margrid the Sly Form|"
  + "Master of Whispers Form|Goren Form|Norgu Form|Morgahn Form|Razah Form|"
  + "Olias Form|Zenmai Form|Ogden Form|Vekk Form|Gwen Form|Xandra Form|Kahmu Form|"
  + "Jora Form|Pyre Fierceshot Form|Anton Form|Hayda Form|Livia Form|"
  + "Keiran Thackeray Form|Miku Form|MOX Form|Shiro Tagachi Form||"
  + "Prince Rurik Form|Margonite Form|Destroyer Form|Queen Salma Form|"
  + "Slightly Mad King Thorn Form|Kuunavang Form|Lone Wolf|Stand Together|"
  + "Unyielding Spirit|Reckless Advance|Aura of Thorns Pv P|Dust Cloak Pv P|"
  + "Lyssas Haste Pv P|Knight Form|Lord Archer Form|Bodyguard Form|"
  + "Guild Thief Form|Ghostly Priest Form|Flame Sentinel Form||Solidarity|"
  + "There Can Be Only One|Fight Against Despair|Deaths Succor|"
  + "Battle of Attrition|Fight or Flight|Renewing Escape|Battle Frenzy|"
  + "The Way of One|Onslaught Pv P|Heart of Fury Pv P|Wounding Strike Pv P|"
  + "Pious Fury Pv P|Party Mode|Smash of the Titans|Mirror Shatter||"
  + "Illusion of Haste Pv P|Illusion of Pain Pv P|Aura of Restoration Pv P|"
  + "Shapeshift|GOLEM disguise|Phase Shield|Reactor Burst|Ill Be Back1|"
  + "Annihilator Strike|Annihilator Beam|Annihilator Knuckle|Annihilator Toss||"
  + "Web of Disruption Pv P|Chain Combo|||All In|Jack of All Trades|Amateur Hour|"
  + "Odrans Razor|Like a Boss|The Boss|Lightning Hammer Pv P|Elemental Flame Pv P|"
  + "Slippery Ground Pv P|"
  + "Disguised when using everlasting tonics except Everlasting Legionnaire Tonic|"
  + "Disguised when using non everlasting tonics|Disguised verification requested|"
  + "Tonic Tipsiness|Parting Gift|Gift of Battle|Rolling Start|"
  + "Disguised when using Everlasting Legionnaire Tonic||||||||||||||||Time Ward|"
  + "Soul Taker|Over the Limit|Judgement Strike|Seven Weapon Stance|"
  + "Together as one|Shadow Theft|Weapons of Three Forges|Vow of Revolution|"
  + "Heroic Refrain|||Reforged Mode|Dhuums Covenant Broken|Count";

let table: readonly string[] | null = null;

/** The display name for a skill id, or `null` when the vocabulary has none. */
export function skillName(id: number): string | null {
  table ??= NAMES.split("|");
  return table[id] || null;
}
