// The one producer of build/preload/preload.cjs.
//
// A sandboxed preload cannot require a local file — Electron's sandbox loader
// whitelists `electron`, `events`, `timers` and `url` — which is why the
// channel names used to be hand-copied out of src/shared/contracts.ts and why
// tests existed to police the copy. The constants are spliced above the
// hand-written body instead, so there is one source and nothing to police.
//
// Only literals that were genuinely duplicated are generated. The body stays
// readable and reviewed: src/preload/preload.body.cjs.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

export const BODY = "src/preload/preload.body.cjs";
export const OUTPUT = "build/preload/preload.cjs";

/**
 * The canonical exports spliced into the preload. Every one of them was a copy
 * in the preload before; a name added here must be used by the body.
 */
export const PRELOAD_CONSTANTS = [
  "IPC",
  "RENDERER_INIT_ARGUMENT",
  "ENHANCEMENTS",
  "WASM_BRIDGE_MARKERS",
];

/**
 * One contract export as the source text that reproduces it. The value is
 * whatever `src/shared/contracts.ts` exports under that name, so it is read as
 * `unknown` and narrowed here rather than assumed to be an object.
 *
 * @param {unknown} value
 */
const literal = (value) =>
  value !== null && typeof value === "object"
    ? `Object.freeze(${JSON.stringify(value, null, 2)})`
    : JSON.stringify(value);

/**
 * The complete preload source, given the contracts module it is generated from.
 * Exported so a test can generate one from altered contracts and execute it,
 * rather than asserting about this file's text.
 *
 * @param {Record<string, unknown>} contracts src/shared/contracts.ts, compiled or not.
 * @param {string} [root] repository root, for locating the body.
 */
export function preloadSource(contracts, root = process.cwd()) {
  const header = PRELOAD_CONSTANTS.map((name) => {
    if (contracts[name] === undefined) {
      throw new Error(`src/shared/contracts.ts exports no ${name}`);
    }
    return `const ${name} = ${literal(contracts[name])};`;
  }).join("\n");
  const body = readFileSync(path.join(root, BODY), "utf8");
  return `// GENERATED by scripts/generate-preload.mjs — do not edit.\n// Constants: src/shared/contracts.ts. Body: ${BODY}.\n${header}\n\n${body}`;
}

function generate(root = process.cwd()) {
  const compiled = path.join(root, "build/shared/contracts.js");
  return import(pathToFileURL(compiled).href).then((contracts) => {
    mkdirSync(path.join(root, path.dirname(OUTPUT)), { recursive: true });
    writeFileSync(path.join(root, OUTPUT), preloadSource(contracts, root));
    console.log(`generated preload -> ${OUTPUT}`);
  });
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  await generate();
}
