// The one producer of build/preload/preload.cjs.
//
// A sandboxed preload cannot require a local file — Electron's sandbox loader
// whitelists `electron`, `events`, `timers` and `url` — which is why the
// channel names used to be hand-copied out of src/shared/contracts.ts and why
// tests existed to police the copy. The constants are spliced above the
// hand-written body instead, so there is one source and nothing to police.
//
// Only literals that were genuinely duplicated are generated. The body stays
// readable and reviewed: src/preload/preload.body.cjs.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
// The source, not build/shared/contracts.js. This ran under `tsc`'s output for
// as long as it was JavaScript and could not read TypeScript; now that it runs
// under the loader, reading the compiled copy would only mean the generator's
// input depended on a build step and a stale build/ could produce a stale
// preload — with the test that proves this generator asserting against the
// source the build does not use.
import * as contracts from "../src/shared/contracts.js";

export const BODY = "src/preload/preload.body.cjs";
export const OUTPUT = "build/preload/preload.cjs";

/**
 * The canonical exports spliced into the preload. Every one of them was a copy
 * in the preload before; a name added here must be used by the body.
 */
export const PRELOAD_CONSTANTS = [
  "IPC",
  "RENDERER_INIT_ARGUMENT",
  "ENHANCEMENTS",
  "ENHANCEMENT_PROGRAMS",
  "WASM_BRIDGE_MARKERS",
];

/**
 * One contract export as the source text that reproduces it. The value is
 * whatever `src/shared/contracts.ts` exports under that name, so it is read as
 * `unknown` and narrowed here rather than assumed to be an object.
 */
const literal = (value: unknown) =>
  value !== null && typeof value === "object"
    ? `Object.freeze(${JSON.stringify(value, null, 2)})`
    : JSON.stringify(value);

/**
 * The complete preload source, given the contracts module it is generated from.
 * Exported so a test can generate one from altered contracts and execute it,
 * rather than asserting about this file's text.
 *
 * `contracts` is src/shared/contracts.ts, compiled or not; `root` is the
 * repository root, for locating the body.
 */
export function preloadSource(
  contracts: Record<string, unknown>,
  root: string = process.cwd(),
) {
  const header = PRELOAD_CONSTANTS.map((name) => {
    if (contracts[name] === undefined) {
      throw new Error(`src/shared/contracts.ts exports no ${name}`);
    }
    return `const ${name} = ${literal(contracts[name])};`;
  }).join("\n");
  const body = readFileSync(path.join(root, BODY), "utf8");
  return `// GENERATED by scripts/generate-preload.ts — do not edit.\n// Constants: src/shared/contracts.ts. Body: ${BODY}.\n${header}\n\n${body}`;
}

function generate(root: string = process.cwd()) {
  mkdirSync(path.join(root, path.dirname(OUTPUT)), { recursive: true });
  writeFileSync(path.join(root, OUTPUT), preloadSource({ ...contracts }, root));
  console.log(`generated preload -> ${OUTPUT}`);
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  generate();
}
