// The one producer of the Core and Tools sandboxed preloads.
//
// A sandboxed preload cannot require a local file — Electron's sandbox loader
// whitelists `electron`, `events`, `timers` and `url` — which is why the
// channel names used to be hand-copied out of src/shared/contracts.ts and why
// tests existed to police the copy. The constants are spliced above the
// hand-written body instead, so there is one source and nothing to police.
//
// Only literals that were genuinely duplicated are generated. The body stays
// readable and reviewed: src/preload/preload.body.cjs.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
// The source, not build/shared/contracts.js. This ran under `tsc`'s output for
// as long as it was JavaScript and could not read TypeScript; now that it runs
// under the loader, reading the compiled copy would only mean the generator's
// input depended on a build step and a stale build/ could produce a stale
// preload — with the test that proves this generator asserting against the
// source the build does not use.
import * as contracts from "../src/shared/contracts.js";
import * as enhancementContracts from "../src/shared/enhancement-contracts.js";
import { LAUNCHER_IPC } from "../src/shared/launcher-contracts.js";

export const BODY = "src/preload/preload.body.cjs";
export const TOOLS_EXTENSION = "src/preload/preload.tools.cjs";
export const CORE_OUTPUT = "build/preload/preload-core.cjs";
export const TOOLS_OUTPUT = "build/preload/preload-tools.cjs";
export const LAUNCHER_BODY = "src/preload/preload.launcher.cjs";
export const LAUNCHER_OUTPUT = "build/preload/preload-launcher.cjs";

/**
 * The canonical exports spliced into the preload. Every one of them was a copy
 * in the preload before; a name added here must be used by the body.
 */
export const PRELOAD_CONSTANTS = [
  "IPC",
  "RENDERER_INIT_ARGUMENT",
  "ENHANCEMENTS",
  "ENHANCEMENT_PROGRAMS",
  "DIAGNOSTIC_PROFILES",
  "WASM_BRIDGE_MARKERS",
];

/**
 * One contract export as the source text that reproduces it. The value is
 * whatever `src/shared/contracts.ts` exports under that name, so it is read as
 * `unknown` and narrowed here rather than assumed to be an object.
 */
const literal = (value: unknown) =>
  value !== null && typeof value === "object"
    ? `Object.freeze(${JSON.stringify(value, null, 2)})`
    : JSON.stringify(value);

/**
 * The complete preload source, given the contracts module it is generated from.
 * Exported so a test can generate one from altered contracts and execute it,
 * rather than asserting about this file's text.
 *
 * `contracts` is src/shared/contracts.ts, compiled or not; `root` is the
 * repository root, for locating the body.
 */
export function preloadSource(
  contracts: Record<string, unknown>,
  root: string = process.cwd(),
  tools = true,
) {
  const header = PRELOAD_CONSTANTS.map((name) => {
    if (contracts[name] === undefined) {
      throw new Error(`src/shared/contracts.ts exports no ${name}`);
    }
    return `const ${name} = ${literal(contracts[name])};`;
  }).join("\n");
  const body = readFileSync(path.join(root, BODY), "utf8");
  const extension = tools
    ? `${readFileSync(path.join(root, TOOLS_EXTENSION), "utf8")}\ninstallToolsApi(api, ipcRenderer, IPC, listen);`
    : "";
  return `// GENERATED by scripts/generate-preload.ts — do not edit.\n// Constants: src/shared/contracts.ts. Body: ${BODY}.\n${header}\n\n${body.replace("/* TOOLS_API_EXTENSION */", extension)}`;
}

export function launcherPreloadSource(root: string = process.cwd()) {
  const body = readFileSync(path.join(root, LAUNCHER_BODY), "utf8");
  return `// GENERATED by scripts/generate-preload.ts — do not edit.\n// Constants: src/shared/launcher-contracts.ts. Body: ${LAUNCHER_BODY}.\nconst LAUNCHER_IPC = ${literal(LAUNCHER_IPC)};\n\n${body}`;
}

function generate(root: string = process.cwd()) {
  mkdirSync(path.join(root, path.dirname(CORE_OUTPUT)), { recursive: true });
  const inputs = { ...contracts, ...enhancementContracts };
  writeFileSync(
    path.join(root, CORE_OUTPUT),
    preloadSource({ ...inputs, IPC: contracts.CORE_IPC }, root, false),
  );
  writeFileSync(path.join(root, TOOLS_OUTPUT), preloadSource(inputs, root, true));
  writeFileSync(path.join(root, LAUNCHER_OUTPUT), launcherPreloadSource(root));
  console.log(`generated preloads -> ${CORE_OUTPUT}, ${TOOLS_OUTPUT}, ${LAUNCHER_OUTPUT}`);
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  generate();
}
