/**
 * Converts GWToolbox++'s generated CartographyData.h into the compact,
 * pointer-free TypeScript masks consumed by the renderer.
 */
import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { resolve } from "node:path";

const SOURCE_COMMIT = "cbe940d3edcc0c47fc02a59079a8f6e08d11f4cf";
const SOURCE_SHA256 = "a20298a47f32eac2b72256659240a7abd7ebe93c573af1bd7ce069ebf8c18453";
const destination = resolve(
  "src/renderer/cartography-spike/toolbox-cartography-data.ts",
);
const sourceArgument = process.argv[2];
if (!sourceArgument) {
  throw new Error("usage: import-toolbox-cartography-data.ts <CartographyData.h>");
}

const source = await readFile(resolve(sourceArgument), "utf8");
const sourceHash = createHash("sha256").update(source).digest("hex");
if (sourceHash !== SOURCE_SHA256) {
  throw new Error(`unexpected CartographyData.h SHA-256: ${sourceHash}`);
}
const arrays = new Map<string, Uint8Array>();
for (const match of source.matchAll(
  /inline constexpr uint8_t (\w+)\[\] = \{([\s\S]*?)\n\s*\};/g,
)) {
  const values = [...match[2]!.matchAll(/\d+/g)].map(([value]) => Number(value));
  if (values.some((value) => !Number.isSafeInteger(value) || value < 0 || value > 255)) {
    throw new Error(`invalid byte array ${match[1]}`);
  }
  arrays.set(match[1]!, Uint8Array.from(values));
}

type ImportedMask = Readonly<{
  x0: number;
  y0: number;
  width: number;
  height: number;
  bytes: Uint8Array;
}>;

const continents: Array<Readonly<{ id: number; masks: readonly ImportedMask[] }>> = [];
const table = source.match(/inline constexpr Continent kContinents\[\] = \{([\s\S]*?)\n\s*\};/)
  ?.[1] ?? "";
for (const line of table.split("\n")) {
  const id = line.match(/^\s*\{(\d+),/)?.[1];
  if (id === undefined) continue;
  const masks = [...line.matchAll(
    /\{(-?\d+),\s*(-?\d+),\s*(\d+),\s*(\d+),\s*(\w+),\s*(\d+)\}/g,
  )].map((match): ImportedMask => {
    const bytes = arrays.get(match[5]!);
    if (!bytes || bytes.length !== Number(match[6])) {
      throw new Error(`missing or truncated byte array ${match[5]}`);
    }
    return Object.freeze({
      x0: Number(match[1]),
      y0: Number(match[2]),
      width: Number(match[3]),
      height: Number(match[4]),
      bytes,
    });
  });
  if (masks.length !== 6) throw new Error(`continent ${id} has ${masks.length} masks`);
  continents.push(Object.freeze({ id: Number(id), masks: Object.freeze(masks) }));
}
if (continents.length !== 6) throw new Error(`expected 6 continents, found ${continents.length}`);

// Runtime guidance uses Toolbox's normal, reachable mode. Glitch and
// permissive diagnostic masks stay out of the shipped application.
const names = ["standable", "creditable"] as const;
const maskSource = (mask: ImportedMask): string => [
  "mask(",
  `${mask.x0}, ${mask.y0}, ${mask.width}, ${mask.height}, `,
  `${JSON.stringify(Buffer.from(mask.bytes).toString("base64"))})`,
].join("");
const rows = continents.map(({ id, masks }) => [
  "  Object.freeze({\n",
  `    id: ${id},\n`,
  ...masks.slice(0, names.length)
    .map((mask, index) => `    ${names[index]}: ${maskSource(mask)},\n`),
  "  }),\n",
].join(""));

const output = `/**
 * Owns the compact continent masks imported from GWToolbox++ ${SOURCE_COMMIT}.
 * Generated from CartographyData.h; do not edit this file by hand.
 */
export type ToolboxCartographyMask = Readonly<{
  x0: number;
  y0: number;
  width: number;
  height: number;
  bits: Uint8Array;
}>;

export type ToolboxCartographyContinent = Readonly<{
  id: number;
  standable: ToolboxCartographyMask;
  creditable: ToolboxCartographyMask;
}>;

export const TOOLBOX_CARTOGRAPHY_SOURCE = Object.freeze({
  repository: "https://github.com/gwdevhub/GWToolboxpp",
  commit: "${SOURCE_COMMIT}",
  path: "GWToolboxdll/Widgets/CartographyData.h",
  sha256: "${SOURCE_SHA256}",
});

function mask(
  x0: number,
  y0: number,
  width: number,
  height: number,
  encoded: string,
): ToolboxCartographyMask {
  const binary = atob(encoded);
  const bits = Uint8Array.from(binary, (value) => value.charCodeAt(0));
  if (bits.length !== Math.ceil(width * height / 8)) {
    throw new Error("Invalid bundled Toolbox++ cartography mask");
  }
  return Object.freeze({ x0, y0, width, height, bits });
}

export const TOOLBOX_CARTOGRAPHY_CONTINENTS: readonly ToolboxCartographyContinent[] =
  Object.freeze([\n${rows.join("")}]);
`;

await writeFile(destination, output);
