/** Executes the feature's generated bytecode in minimal WebAssembly modules. */
import assert from "node:assert/strict";
import test from "node:test";
import {
  quickItemMoveHandler,
  quickItemMoveItemLookup,
  quickItemMoveDrain,
  quickItemMoveFindAncestor,
  quickItemMoveSlotWrapper,
  quickItemMoveStorageExecutor,
  type QuickItemMoveGlobals,
} from "../../src/main/certification/enhancement-quick-item-move-transform.js";
import { ENHANCEMENT_BUILDS } from "../../src/main/certification/enhancement-builds.js";
import {
  concat,
  encodeCode,
  encodeSection,
  sleb,
  uleb,
  WASM_HEADER,
} from "../../src/main/core/wasm-binary.js";

const globals: QuickItemMoveGlobals = Object.freeze({
  enabled: 0,
  modifiers: 1,
  scratch: 2,
  draining: 3,
  intentModifiers: 4,
});

function name(value: string): Uint8Array {
  const bytes = new TextEncoder().encode(value);
  return concat(uleb(bytes.length), bytes);
}

function exported(nameValue: string, kind: number, index: number): Uint8Array {
  return concat(name(nameValue), Uint8Array.of(kind), uleb(index));
}

const op = (...bytes: number[]) => Uint8Array.of(...bytes);
const i32 = (value: number) => concat(op(0x41), sleb(value));
const local = (index: number) => concat(op(0x20), uleb(index));
const global = (index: number) => concat(op(0x23), uleb(index));
const setGlobal = (index: number) => concat(op(0x24), uleb(index));
const load = (offset = 0) => concat(op(0x28), uleb(2), uleb(offset));
const mutableGlobal = (value = 0) => concat(op(0x7f, 0x01), i32(value), op(0x0b));

const handlerState = Object.freeze({
  itemPointer: 7,
  cartAncestor: 8,
  dialogAncestor: 9,
  cartFrame: 10,
  storageItem: 11,
  storageQuantity: 12,
  storageDirection: 13,
  frameMessage: 14,
  frameAction: 15,
  frameItem12: 16,
  frameItem20: 17,
  frameQuantity: 18,
  uiMessage: 19,
});

const storageState = Object.freeze({
  itemPointer: 7,
  page: 8,
  storageFrame: 9,
  claimAllowed: 10,
  claimBag: 11,
  claimSlot: 12,
  uiMessage: 13,
  uiItem: 14,
  uiQuantity: 15,
  uiBag: 16,
  uiSlot: 17,
});

function handlerModule(): Uint8Array {
  const build = ENHANCEMENT_BUILDS[0]!;
  const certificate = build.quickItemMove!;
  const layout = { ...build.preGameControls!.layout, contextRoot: 32, gameContextSlot: 0 };
  const types = concat(
    uleb(5),
    op(0x60), uleb(1), op(0x7f), uleb(1), op(0x7f),
    op(0x60), uleb(3), op(0x7f, 0x7f, 0x7f), uleb(0),
    op(0x60), uleb(2), op(0x7f, 0x7f), uleb(1), op(0x7f),
    op(0x60), uleb(4), op(0x7f, 0x7f, 0x7f, 0x7f), uleb(0),
    op(0x60), uleb(3), op(0x7f, 0x7f, 0x7f), uleb(1), op(0x7f),
  );
  const returnGlobal = (index: number) => concat(uleb(0), global(index), op(0x0b));
  const frameDispatch = concat(
    uleb(0),
    local(1), setGlobal(handlerState.frameMessage),
    local(2), load(4), setGlobal(handlerState.frameAction),
    local(2), load(12), setGlobal(handlerState.frameItem12),
    local(2), load(20), setGlobal(handlerState.frameItem20),
    local(2), load(24), setGlobal(handlerState.frameQuantity),
    op(0x0b),
  );
  const findAncestor = concat(
    uleb(0), local(1), i32(certificate.tradeCartFrameHash), op(0x46, 0x04, 0x7f),
    global(handlerState.cartAncestor), op(0x05), global(handlerState.dialogAncestor),
    op(0x0b, 0x0b),
  );
  const storageExecutor = concat(
    uleb(0),
    local(0), setGlobal(handlerState.storageItem),
    local(1), setGlobal(handlerState.storageQuantity),
    local(2), setGlobal(handlerState.storageDirection),
    i32(1), op(0x0b),
  );
  const uiDispatcher = concat(
    uleb(0), local(0), setGlobal(handlerState.uiMessage), op(0x0b),
  );
  const body = quickItemMoveHandler({
    certificate,
    layout,
    globals,
    itemLookup: 0,
    numberPreference: 1,
    uiDispatcher: 2,
    findFrame: 3,
    claimDestination: 4,
    frameDispatch: 5,
    frameDispatchOffset: 0,
    findAncestor: 6,
    storageExecutor: 7,
    pendingGlobal: 20,
    argumentGlobalBase: 21,
  });
  const stateExports = Object.entries(handlerState).map(([key, index]) =>
    exported(key, 0x03, index));
  return concat(
    WASM_HEADER,
    encodeSection({ id: 1, body: types }),
    encodeSection({ id: 3, body: concat(
      uleb(9), uleb(0), uleb(0), uleb(1), uleb(0), uleb(2), uleb(3), uleb(2), uleb(4), uleb(2),
    ) }),
    encodeSection({ id: 5, body: concat(uleb(1), op(0x00), uleb(1)) }),
    encodeSection({ id: 6, body: concat(
      uleb(23), mutableGlobal(1), mutableGlobal(1), mutableGlobal(2_048),
      mutableGlobal(1), mutableGlobal(1), mutableGlobal(), mutableGlobal(),
      mutableGlobal(256), ...Array.from({ length: 12 }, () => mutableGlobal()),
      mutableGlobal(), mutableGlobal(), mutableGlobal(),
    ) }),
    encodeSection({ id: 7, body: concat(
      uleb(12 + stateExports.length),
      exported("memory", 0x02, 0), exported("handler", 0x00, 8),
      exported("itemLookup", 0x00, 0), exported("storageExecutor", 0x00, 7),
      exported("enabled", 0x03, globals.enabled),
      exported("modifiers", 0x03, globals.modifiers),
      exported("scratch", 0x03, globals.scratch),
      exported("draining", 0x03, globals.draining),
      exported("intentModifiers", 0x03, globals.intentModifiers),
      exported("pending", 0x03, 20), exported("pendingItem", 0x03, 21),
      exported("pendingFrame", 0x03, 22),
      ...stateExports,
    ) }),
    encodeSection({ id: 10, body: encodeCode([
      returnGlobal(handlerState.itemPointer),
      concat(uleb(0), i32(0), op(0x0b)),
      uiDispatcher,
      returnGlobal(handlerState.cartFrame),
      concat(uleb(0), i32(1), op(0x0b)),
      frameDispatch,
      findAncestor,
      storageExecutor,
      body,
    ]) }),
  );
}

function storageExecutorModule(): Uint8Array {
  const build = ENHANCEMENT_BUILDS[0]!;
  const certificate = build.quickItemMove!;
  const layout = { ...build.preGameControls!.layout, contextRoot: 32, gameContextSlot: 0 };
  const types = concat(
    uleb(4),
    op(0x60), uleb(1), op(0x7f), uleb(1), op(0x7f),
    op(0x60), uleb(3), op(0x7f, 0x7f, 0x7f), uleb(0),
    op(0x60), uleb(2), op(0x7f, 0x7f), uleb(1), op(0x7f),
    op(0x60), uleb(3), op(0x7f, 0x7f, 0x7f), uleb(1), op(0x7f),
  );
  const returnGlobal = (index: number) => concat(uleb(0), global(index), op(0x0b));
  const uiDispatcher = concat(
    uleb(0),
    local(0), setGlobal(storageState.uiMessage),
    local(1), load(), setGlobal(storageState.uiItem),
    local(1), load(4), setGlobal(storageState.uiQuantity),
    local(1), load(8), setGlobal(storageState.uiBag),
    local(1), load(12), setGlobal(storageState.uiSlot),
    op(0x0b),
  );
  const claimDestination = concat(
    uleb(0),
    local(0), setGlobal(storageState.claimBag),
    local(1), setGlobal(storageState.claimSlot),
    global(storageState.claimAllowed), op(0x0b),
  );
  const executor = quickItemMoveStorageExecutor({
    certificate,
    layout,
    globals,
    itemLookup: 0,
    numberPreference: 1,
    uiDispatcher: 2,
    findFrame: 3,
    claimDestination: 4,
  });
  const stateExports = Object.entries(storageState).map(([key, index]) =>
    exported(key, 0x03, index));
  return concat(
    WASM_HEADER,
    encodeSection({ id: 1, body: types }),
    encodeSection({ id: 3, body: concat(
      uleb(6), uleb(0), uleb(0), uleb(1), uleb(0), uleb(2), uleb(3),
    ) }),
    encodeSection({ id: 5, body: concat(uleb(1), op(0x00), uleb(1)) }),
    encodeSection({ id: 6, body: concat(
      uleb(18), mutableGlobal(1), mutableGlobal(1), mutableGlobal(2_048),
      mutableGlobal(), mutableGlobal(), mutableGlobal(), mutableGlobal(),
      mutableGlobal(256), mutableGlobal(),
      mutableGlobal(1), mutableGlobal(1),
      ...Array.from({ length: 7 }, () => mutableGlobal()),
    ) }),
    encodeSection({ id: 7, body: concat(
      uleb(5 + stateExports.length),
      exported("memory", 0x02, 0), exported("executor", 0x00, 5),
      exported("modifiers", 0x03, globals.modifiers),
      exported("draining", 0x03, globals.draining),
      exported("intentModifiers", 0x03, globals.intentModifiers),
      ...stateExports,
    ) }),
    encodeSection({ id: 10, body: encodeCode([
      returnGlobal(storageState.itemPointer),
      returnGlobal(storageState.page),
      uiDispatcher,
      returnGlobal(storageState.storageFrame),
      claimDestination,
      executor,
    ]) }),
  );
}

async function instantiate(bytes: Uint8Array): Promise<WebAssembly.Instance> {
  const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
  assert.equal(WebAssembly.validate(buffer), true);
  return WebAssembly.instantiate(await WebAssembly.compile(buffer));
}

function quickDrainModule(): Uint8Array {
  const pending = 7;
  const argumentsBase = 8;
  const handler = concat(
    uleb(0), local(0), setGlobal(10), local(1), setGlobal(11),
    global(globals.draining), setGlobal(12), global(13), i32(1), op(0x6a), setGlobal(13),
    i32(1), op(0x0b),
  );
  const drain = concat(
    uleb(0), quickItemMoveDrain(pending, argumentsBase, globals, 0), op(0x0b),
  );
  return concat(
    WASM_HEADER,
    encodeSection({ id: 1, body: concat(
      uleb(2),
      op(0x60), uleb(2), op(0x7f, 0x7f), uleb(1), op(0x7f),
      op(0x60), uleb(0), uleb(0),
    ) }),
    encodeSection({ id: 3, body: concat(uleb(2), uleb(0), uleb(1)) }),
    encodeSection({ id: 6, body: concat(
      uleb(14), ...Array.from({ length: 14 }, () => mutableGlobal()),
    ) }),
    encodeSection({ id: 7, body: concat(
      uleb(8), exported("drain", 0x00, 1),
      exported("pending", 0x03, pending), exported("item", 0x03, argumentsBase),
      exported("frame", 0x03, argumentsBase + 1), exported("seenItem", 0x03, 10),
      exported("seenFrame", 0x03, 11), exported("seenDraining", 0x03, 12),
      exported("calls", 0x03, 13),
    ) }),
    encodeSection({ id: 10, body: encodeCode([handler, drain]) }),
  );
}

function ancestorModule(): Uint8Array {
  const types = concat(
    uleb(2),
    op(0x60), uleb(1), op(0x7f), uleb(1), op(0x7f),
    op(0x60), uleb(2), op(0x7f, 0x7f), uleb(1), op(0x7f),
  );
  const resolver = concat(
    uleb(0), local(0), i32(7), op(0x46, 0x04, 0x7f),
    i32(64), op(0x05), i32(128), op(0x0b, 0x0b),
  );
  const parent = concat(
    uleb(0), local(0), setGlobal(0), local(0), i32(7), op(0x46, 0x04, 0x7f),
    i32(6), op(0x05), i32(0), op(0x0b, 0x0b),
  );
  return concat(
    WASM_HEADER,
    encodeSection({ id: 1, body: types }),
    encodeSection({ id: 3, body: concat(uleb(3), uleb(0), uleb(0), uleb(1)) }),
    encodeSection({ id: 5, body: concat(uleb(1), op(0x00), uleb(1)) }),
    encodeSection({ id: 6, body: concat(uleb(1), mutableGlobal()) }),
    encodeSection({ id: 7, body: concat(
      uleb(3), exported("memory", 0x02, 0), exported("ancestor", 0x00, 2),
      exported("parentInput", 0x03, 0),
    ) }),
    encodeSection({ id: 10, body: encodeCode([
      resolver, parent, quickItemMoveFindAncestor(0, 1, 0, 4, 8),
    ]) }),
  );
}

function itemLookupModule(): Uint8Array {
  const layout = { ...ENHANCEMENT_BUILDS[0]!.preGameControls!.layout,
    contextRoot: 32, gameContextSlot: 0 };
  return concat(
    WASM_HEADER,
    encodeSection({ id: 1, body: concat(
      uleb(1), op(0x60), uleb(1), op(0x7f), uleb(1), op(0x7f),
    ) }),
    encodeSection({ id: 3, body: concat(uleb(1), uleb(0)) }),
    encodeSection({ id: 5, body: concat(uleb(1), op(0x00), uleb(1)) }),
    encodeSection({ id: 7, body: concat(
      uleb(2), exported("memory", 0x02, 0), exported("lookup", 0x00, 0),
    ) }),
    encodeSection({ id: 10, body: encodeCode([quickItemMoveItemLookup(layout)]) }),
  );
}

function slotWrapperModule(material: boolean): Uint8Array {
  const types = concat(
    uleb(3),
    op(0x60), uleb(3), op(0x7f, 0x7f, 0x7f), uleb(0),
    op(0x60), uleb(2), op(0x7f, 0x7f), uleb(1), op(0x7f),
    op(0x60), uleb(1), op(0x7f), uleb(1), op(0x7f),
  );
  const original = concat(
    uleb(0), global(0), i32(1), op(0x6a), setGlobal(0), op(0x0b),
  );
  const handler = concat(
    uleb(0), local(0), setGlobal(1), local(1), setGlobal(2), i32(1), op(0x0b),
  );
  const resolver = concat(uleb(0), global(3), op(0x0b));
  const wrapper = quickItemMoveSlotWrapper(0, 1, material, 2);
  return concat(
    WASM_HEADER,
    encodeSection({ id: 1, body: types }),
    encodeSection({ id: 3, body: concat(uleb(4), uleb(0), uleb(1), uleb(2), uleb(0)) }),
    encodeSection({ id: 5, body: concat(uleb(1), op(0x00), uleb(1)) }),
    encodeSection({ id: 6, body: concat(
      uleb(4), mutableGlobal(), mutableGlobal(), mutableGlobal(), mutableGlobal(256),
    ) }),
    encodeSection({ id: 7, body: concat(
      uleb(6), exported("memory", 0x02, 0), exported("slot", 0x00, 3),
      exported("originalCalls", 0x03, 0), exported("item", 0x03, 1),
      exported("frame", 0x03, 2), exported("resolvedFrame", 0x03, 3),
    ) }),
    encodeSection({ id: 10, body: encodeCode([original, handler, resolver, wrapper]) }),
  );
}

test("item-click wrappers mirror GWCA's inventory and material lookup paths", async () => {
  const inventory = await instantiate(slotWrapperModule(false));
  const inventoryExports = inventory.exports;
  const inventoryView = new DataView((inventoryExports.memory as WebAssembly.Memory).buffer);
  const inventorySlot = inventoryExports.slot as (message: number, action: number, context: number) => void;
  inventoryView.setUint32(64 + 4, 49, true);
  inventoryView.setUint32(64 + 8, 80, true);
  inventoryView.setUint32(80, 96, true);
  inventoryView.setUint32(96 + 8, 160, true);
  inventoryView.setUint32(96 + 16, 1, true);
  inventoryView.setUint32(160, 1_234, true);
  inventoryView.setUint32(128, 99, true);
  inventoryView.setUint32(128 + 4, 2, true);
  inventoryView.setUint32(128 + 8, 7, true);
  inventorySlot(64, 128, 0);
  assert.equal((inventoryExports.item as WebAssembly.Global).value, 1_234);
  assert.equal((inventoryExports.frame as WebAssembly.Global).value, 99);
  assert.equal((inventoryExports.originalCalls as WebAssembly.Global).value, 0);

  (inventoryExports.item as WebAssembly.Global).value = 0;
  inventoryView.setUint32(128 + 8, 8, true);
  inventorySlot(64, 128, 0);
  assert.equal((inventoryExports.item as WebAssembly.Global).value, 1_234);
  inventoryView.setUint32(128 + 8, 6, true);
  inventorySlot(64, 128, 0);
  assert.equal((inventoryExports.originalCalls as WebAssembly.Global).value, 1);

  const material = await instantiate(slotWrapperModule(true));
  const materialExports = material.exports;
  const materialView = new DataView((materialExports.memory as WebAssembly.Memory).buffer);
  const materialSlot = materialExports.slot as (callback: number, action: number, context: number) => void;
  materialView.setUint32(64 + 4, 49, true);
  materialView.setUint32(128, 777, true);
  materialView.setUint32(128 + 8, 8, true);
  materialView.setUint32(256 + 0xa8, 400, true);
  materialView.setUint32(256 + 0xb0, 1, true);
  materialView.setUint32(400 + 4, 500, true);
  materialView.setUint32(500 + 28, 4_321, true);
  materialSlot(64, 128, 0);
  assert.equal((materialExports.item as WebAssembly.Global).value, 4_321);
  assert.equal((materialExports.frame as WebAssembly.Global).value, 777);
  assert.equal((materialExports.originalCalls as WebAssembly.Global).value, 0);
});

test("ancestor lookup keeps frame ids separate from resolved pointers", async () => {
  const instance = await instantiate(ancestorModule());
  const view = new DataView((instance.exports.memory as WebAssembly.Memory).buffer);
  view.setUint32(64, 111, true);
  view.setUint32(64 + 4, 7, true);
  view.setUint32(128, 222, true);
  view.setUint32(128 + 4, 6, true);
  const ancestor = instance.exports.ancestor as (frameId: number, hash: number) => number;
  assert.equal(ancestor(7, 222), 128);
  assert.equal((instance.exports.parentInput as WebAssembly.Global).value, 7);
});

test("item lookup mirrors GWCA's bounded ItemContext array access", async () => {
  const instance = await instantiate(itemLookupModule());
  const view = new DataView((instance.exports.memory as WebAssembly.Memory).buffer);
  const lookup = instance.exports.lookup as (itemId: number) => number;
  view.setUint32(32, 100, true);
  view.setUint32(100, 200, true);
  view.setUint32(200 + 0x40, 300, true);
  view.setUint32(300 + 0xb8, 400, true);
  view.setUint32(300 + 0xc0, 10, true);
  view.setUint32(400 + 5 * 4, 500, true);
  assert.equal(lookup(5), 500);
  assert.equal(lookup(0), 0);
  assert.equal(lookup(10), 0);
  view.setUint32(400 + 5 * 4, 65_500, true);
  assert.equal(lookup(5), 0, "an item record outside linear memory fails closed");
});

test("captured clicks drain once from the deferred game-thread branch", async () => {
  const instance = await instantiate(quickDrainModule());
  const exportedGlobal = (nameValue: string) =>
    instance.exports[nameValue] as WebAssembly.Global;
  exportedGlobal("pending").value = -20;
  exportedGlobal("item").value = 1_234;
  exportedGlobal("frame").value = 77;
  (instance.exports.drain as () => void)();
  assert.equal(exportedGlobal("pending").value, 0);
  assert.equal(exportedGlobal("seenItem").value, 1_234);
  assert.equal(exportedGlobal("seenFrame").value, 77);
  assert.equal(exportedGlobal("seenDraining").value, 1);
  assert.equal(exportedGlobal("calls").value, 1);
  (instance.exports.drain as () => void)();
  assert.equal(exportedGlobal("calls").value, 1);
});

test("handler routes inventory, storage, own offers, and partner offers safely", async () => {
  const instance = await instantiate(handlerModule());
  const exports = instance.exports as Record<string, WebAssembly.ExportValue>;
  const memory = exports.memory as WebAssembly.Memory;
  const handler = exports.handler as (itemId: number, frameId: number) => number;
  const state = (nameValue: keyof typeof handlerState) => exports[nameValue] as WebAssembly.Global;
  const view = new DataView(memory.buffer);
  const itemId = 1_234;
  const item = 256;
  const bag = 512;
  const game = 160;
  const trade = 768;
  const offer = 896;
  view.setUint32(32, 128, true);
  view.setUint32(128, game, true);
  view.setUint32(item + 12, bag, true);
  view.setUint16(item + 76, 9, true);
  view.setUint32(bag + 4, 1, true);
  assert.equal((exports.enabled as WebAssembly.Global).value, 1);
  assert.equal((exports.modifiers as WebAssembly.Global).value, 1);
  assert.equal((exports.scratch as WebAssembly.Global).value, 2_048);
  assert.equal(state("itemPointer").value, item);
  assert.equal((exports.itemLookup as (id: number) => number)(itemId), item);

  view.setUint32(bag, 1, true);
  state("cartFrame").value = 1;
  (exports.draining as WebAssembly.Global).value = 0;
  assert.equal(handler(itemId, 10), 1);
  assert.equal((exports.pending as WebAssembly.Global).value, -20);
  assert.equal((exports.pendingItem as WebAssembly.Global).value, itemId);
  assert.equal((exports.pendingFrame as WebAssembly.Global).value, 10);
  assert.equal(state("storageDirection").value, 0, "the UI callback must not move synchronously");
  (exports.pending as WebAssembly.Global).value = 0;
  (exports.draining as WebAssembly.Global).value = 1;
  state("cartFrame").value = 0;

  const resetSignals = () => {
    for (const key of ["storageItem", "storageQuantity", "storageDirection", "frameMessage",
      "frameAction", "frameItem12", "frameItem20", "frameQuantity", "uiMessage"] as const) {
      state(key).value = 0;
    }
    state("cartAncestor").value = 0;
    state("dialogAncestor").value = 0;
    view.setUint32(game + 0x58, 0, true);
  };

  (exports.enabled as WebAssembly.Global).value = 0;
  assert.equal(handler(itemId, 10), 0);
  assert.equal(state("storageDirection").value, 0);
  (exports.enabled as WebAssembly.Global).value = 1;
  (exports.modifiers as WebAssembly.Global).value = 0;
  (exports.intentModifiers as WebAssembly.Global).value = 0;
  assert.equal(handler(itemId, 10), 0);
  assert.equal(state("storageDirection").value, 0);
  (exports.modifiers as WebAssembly.Global).value = 1;
  (exports.intentModifiers as WebAssembly.Global).value = 1;

  resetSignals();
  view.setUint32(bag, 1, true);
  const inventoryResult = handler(itemId, 10);
  assert.equal(state("storageDirection").value, 1);
  assert.equal(state("storageQuantity").value, 9);
  assert.equal(inventoryResult, 1);

  resetSignals();
  (exports.modifiers as WebAssembly.Global).value = 3;
  (exports.intentModifiers as WebAssembly.Global).value = 3;
  assert.equal(handler(itemId, 10), 1);
  assert.equal(state("storageDirection").value, 1);
  assert.equal(state("storageQuantity").value, 9);
  (exports.modifiers as WebAssembly.Global).value = 1;
  (exports.intentModifiers as WebAssembly.Global).value = 1;

  resetSignals();
  view.setUint32(bag, 4, true);
  view.setUint32(game + 0x58, trade, true);
  view.setUint32(trade, 3, true);
  assert.equal(handler(itemId, 10), 1);
  assert.equal(state("storageDirection").value, 2, "storage withdrawal wins during trade");

  resetSignals();
  view.setUint32(bag, 1, true);
  view.setUint32(game + 0x58, trade, true);
  view.setUint32(trade, 3, true);
  view.setUint32(trade + 20, offer, true);
  view.setUint32(trade + 28, 0, true);
  state("cartFrame").value = 1_000;
  assert.equal(handler(itemId, 10), 1);
  assert.equal(state("frameAction").value, 2);
  assert.equal(state("frameItem20").value, itemId);
  assert.equal(state("frameQuantity").value, 9);

  resetSignals();
  state("cartAncestor").value = 1_000;
  view.setUint32(game + 0x58, trade, true);
  view.setUint32(trade, 1, true);
  view.setUint32(trade + 20, offer, true);
  view.setUint32(trade + 28, 1, true);
  view.setUint32(offer, itemId, true);
  assert.equal(handler(itemId, 10), 1);
  assert.equal(state("frameAction").value, 9);
  assert.equal(state("frameItem12").value, itemId);

  resetSignals();
  state("dialogAncestor").value = 2_000;
  view.setUint32(game + 0x58, trade, true);
  view.setUint32(trade, 1, true);
  assert.equal(handler(itemId, 10), 0);
  assert.equal(state("storageDirection").value, 0, "partner offers remain untouched");
  assert.equal(state("frameMessage").value, 0);
});

test("storage executor validates direction, capacity, material slots, and quantity", async () => {
  const instance = await instantiate(storageExecutorModule());
  const exports = instance.exports;
  const memory = exports.memory as WebAssembly.Memory;
  const execute = exports.executor as (itemId: number, quantity: number, direction: number) => number;
  const state = (nameValue: keyof typeof storageState) => exports[nameValue] as WebAssembly.Global;
  const view = new DataView(memory.buffer);
  const itemId = 1_234;
  const item = 256;
  const inventory = 400;
  const sourceBag = 600;
  const storageBag = 700;
  const materialBag = 720;
  const backpack = 740;
  const slots = 900;
  view.setUint32(32, 128, true);
  view.setUint32(128, 160, true);
  view.setUint32(160 + 0x40, 200, true);
  view.setUint32(200 + 0xf8, inventory, true);
  view.setUint32(item + 12, sourceBag, true);
  view.setUint16(item + 76, 9, true);
  view.setUint32(sourceBag + 4, 3, true);
  view.setUint32(inventory + 8 * 4, storageBag, true);
  view.setUint32(storageBag + 4, 8, true);
  view.setUint32(storageBag + 24, slots, true);
  view.setUint32(storageBag + 32, 2, true);

  view.setUint32(sourceBag, 1, true);
  assert.equal(execute(itemId, 9, 1), 1);
  assert.equal(state("claimBag").value, 8);
  assert.equal(state("claimSlot").value, 0);
  assert.equal(state("uiMessage").value, 0x1000_01af);
  assert.equal(state("uiItem").value, itemId);
  assert.equal(state("uiQuantity").value, 8, "kMoveItem word 2 is the destination bag index");
  assert.equal(state("uiBag").value, 0, "kMoveItem word 3 is the destination slot");
  assert.equal(state("uiSlot").value, 0, "plain Control does not request a quantity prompt");

  (exports.modifiers as WebAssembly.Global).value = 3;
  assert.equal(execute(itemId, 9, 1), 1);
  assert.equal(state("uiSlot").value, 1, "Control+Shift requests the native quantity prompt");
  (exports.modifiers as WebAssembly.Global).value = 1;

  state("uiMessage").value = 0;
  assert.equal(execute(itemId, 0, 1), 0);
  assert.equal(execute(itemId, 10, 1), 0);
  assert.equal(state("uiMessage").value, 0);

  view.setUint32(slots, 1, true);
  view.setUint32(slots + 4, 1, true);
  assert.equal(execute(itemId, 9, 1), 0, "a full normal pane fails closed");
  view.setUint32(slots, 0, true);
  view.setUint32(slots + 4, 0, true);

  state("page").value = 15;
  assert.equal(execute(itemId, 9, 1), 0, "an unknown storage pane fails closed");

  state("page").value = 14;
  view.setUint32(inventory + 6 * 4, materialBag, true);
  view.setUint32(materialBag + 4, 6, true);
  view.setUint32(item + 16, 1_000, true);
  view.setUint32(item + 20, 1, true);
  view.setUint32(1_000, 0x2508_2800, true);
  state("claimAllowed").value = 0;
  assert.equal(execute(itemId, 9, 1), 1);
  assert.equal(state("uiQuantity").value, 6);
  assert.equal(state("uiBag").value, 40, "Zaishen coin material slots are valid");
  assert.equal(state("uiSlot").value, 0);

  state("page").value = 0;
  state("claimAllowed").value = 1;
  view.setUint32(sourceBag, 4, true);
  view.setUint32(inventory + 4, backpack, true);
  view.setUint32(backpack + 4, 1, true);
  view.setUint32(backpack + 24, slots, true);
  view.setUint32(backpack + 32, 2, true);
  assert.equal(execute(itemId, 9, 2), 1);
  assert.equal(state("claimBag").value, 1);
  assert.equal(state("claimSlot").value, 0);

  state("claimAllowed").value = 0;
  assert.equal(execute(itemId, 9, 2), 0, "an in-flight destination is not reused");
});
