import type { TraderPriceCategory } from "../../../src/shared/trade-chat";

export const TRADER_PROFESSIONS = [
  "general", "warrior", "ranger", "monk", "necromancer", "mesmer",
  "elementalist", "assassin", "ritualist", "paragon", "dervish",
] as const;
export type TraderProfession = (typeof TRADER_PROFESSIONS)[number];

export type TraderItem = Readonly<{
  modelId: string;
  name: string;
  category: TraderPriceCategory;
  profession: TraderProfession;
  quantity: number;
}>;

/** Stable Guild Wars identifiers used by Kamadan's public trader quote feed. */
export const TRADER_ITEMS: readonly TraderItem[] = Object.freeze([
  Object.freeze({"modelId":"0b039d","name":"Bolt of Cloth","category":"common-materials","profession":"general","quantity":10}),
  Object.freeze({"modelId":"0b0399","name":"Bone","category":"common-materials","profession":"general","quantity":10}),
  Object.freeze({"modelId":"0b03ba","name":"Chitin Fragment","category":"common-materials","profession":"general","quantity":10}),
  Object.freeze({"modelId":"0b03a5","name":"Feather","category":"common-materials","profession":"general","quantity":10}),
  Object.freeze({"modelId":"0b03bb","name":"Granite Slab","category":"common-materials","profession":"general","quantity":10}),
  Object.freeze({"modelId":"0b03b4","name":"Iron Ingot","category":"common-materials","profession":"general","quantity":10}),
  Object.freeze({"modelId":"0b03a1","name":"Pile of Glittering Dust","category":"common-materials","profession":"general","quantity":10}),
  Object.freeze({"modelId":"0b03a6","name":"Plant Fiber","category":"common-materials","profession":"general","quantity":10}),
  Object.freeze({"modelId":"0b03b9","name":"Scale","category":"common-materials","profession":"general","quantity":10}),
  Object.freeze({"modelId":"0b03ac","name":"Tanned Hide Square","category":"common-materials","profession":"general","quantity":10}),
  Object.freeze({"modelId":"0b03b2","name":"Wood Plank","category":"common-materials","profession":"general","quantity":10}),
  Object.freeze({"modelId":"0a009224d00a01","name":"Vial of Dye [Black]","category":"dyes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0a009224d00201","name":"Vial of Dye [Blue]","category":"dyes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0a009224d00701","name":"Vial of Dye [Brown]","category":"dyes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0a009224d00301","name":"Vial of Dye [Green]","category":"dyes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0a009224d00801","name":"Vial of Dye [Orange]","category":"dyes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0a009224d00d01","name":"Vial of Dye [Pink]","category":"dyes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0a009224d00401","name":"Vial of Dye [Purple]","category":"dyes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0a009224d00501","name":"Vial of Dye [Red]","category":"dyes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0a009224d00901","name":"Vial of Dye [Silver]","category":"dyes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0a009224d00c01","name":"Vial of Dye [White]","category":"dyes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0a009224d00601","name":"Vial of Dye [Yellow]","category":"dyes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b1984","name":"Amber Chunk","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b039f","name":"Bolt of Damask","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b039e","name":"Bolt of Linen","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03a0","name":"Bolt of Silk","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03b6","name":"Deldrimor Steel Ingot","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03a7","name":"Diamond","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03af","name":"Elonian Leather Square","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03ad","name":"Fur Square","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03a2","name":"Glob of Ectoplasm","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b1985","name":"Jadeite Shard","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03ae","name":"Leather Square","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b039a","name":"Lump of Charcoal","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b039b","name":"Monstrous Claw","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03a3","name":"Monstrous Eye","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03a4","name":"Monstrous Fang","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03b1","name":"Obsidian Shard","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03a8","name":"Onyx Gemstone","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03b7","name":"Roll of Parchment","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03b8","name":"Roll of Vellum","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03a9","name":"Ruby","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03aa","name":"Sapphire","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03bc","name":"Spiritwood Plank","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03b5","name":"Steel Ingot","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03ab","name":"Tempered Glass Vial","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0b03b0","name":"Vial of Ink","category":"rare-materials","profession":"general","quantity":1}),
  Object.freeze({"modelId":"084acca53003ea","name":"Aeromancer Insignia [Elementalist]","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"084acfa53003f0","name":"Anchorite's Insignia [Monk]","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"084ab8a53003c4","name":"Artificer's Insignia [Mesmer]","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"0818b521e82302","name":"Assassin Rune of Major Critical Strikes","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"0818b521e81d02","name":"Assassin Rune of Major Dagger Mastery","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"0818b521e81e02","name":"Assassin Rune of Major Deadly Arts","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"0818b521e81f02","name":"Assassin Rune of Major Shadow Arts","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"0818b421e82301","name":"Assassin Rune of Minor Critical Strikes","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"0818b421e81d01","name":"Assassin Rune of Minor Dagger Mastery","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"0818b421e81e01","name":"Assassin Rune of Minor Deadly Arts","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"0818b421e81f01","name":"Assassin Rune of Minor Shadow Arts","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"0818b621e82303","name":"Assassin Rune of Superior Critical Strikes","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"0818b621e81d03","name":"Assassin Rune of Superior Dagger Mastery","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"0818b621e81e03","name":"Assassin Rune of Superior Deadly Arts","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"0818b621e81f03","name":"Assassin Rune of Superior Shadow Arts","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"084ad9a5300400","name":"Beastmaster's Insignia [Ranger]","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"084abfa53003d2","name":"Blessed Insignia","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"084ac7a53003e0","name":"Blighter's Insignia [Necromancer]","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"084ac227e802a9","name":"Bloodstained Insignia [Necromancer]","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"084ac5a53003dc","name":"Bonelace Insignia [Necromancer]","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"084abea53003d0","name":"Brawler's Insignia","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"084ae0a530040e","name":"Centurion's Insignia [Paragon]","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"083cba21e82b02","name":"Dervish Rune of Major Earth Prayers","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"083cba21e82c02","name":"Dervish Rune of Major Mysticism","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"083cba21e82902","name":"Dervish Rune of Major Scythe Mastery","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"083cba21e82a02","name":"Dervish Rune of Major Wind Prayers","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"083cb921e82b01","name":"Dervish Rune of Minor Earth Prayers","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"083cb921e82c01","name":"Dervish Rune of Minor Mysticism","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"083cb921e82901","name":"Dervish Rune of Minor Scythe Mastery","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"083cb921e82a01","name":"Dervish Rune of Minor Wind Prayers","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"083cbb21e82b03","name":"Dervish Rune of Superior Earth Prayers","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"083cbb21e82c03","name":"Dervish Rune of Superior Mysticism","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"083cbb21e82903","name":"Dervish Rune of Superior Scythe Mastery","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"083cbb21e82a03","name":"Dervish Rune of Superior Wind Prayers","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"084acea53003ee","name":"Disciple's Insignia [Monk]","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"084ad3a53003f4","name":"Dreadnought Insignia [Warrior]","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"084ad6a53003fa","name":"Earthbound Insignia [Ranger]","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"0815b221e80802","name":"Elementalist Rune of Major Air Magic","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"0815b221e80902","name":"Elementalist Rune of Major Earth Magic","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"0815b221e80c02","name":"Elementalist Rune of Major Energy Storage","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"0815b221e80a02","name":"Elementalist Rune of Major Fire Magic","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"0815b221e80b02","name":"Elementalist Rune of Major Water Magic","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"08038521e80801","name":"Elementalist Rune of Minor Air Magic","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"08038521e80901","name":"Elementalist Rune of Minor Earth Magic","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"08038521e80c01","name":"Elementalist Rune of Minor Energy Storage","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"08038521e80a01","name":"Elementalist Rune of Minor Fire Magic","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"08038521e80b01","name":"Elementalist Rune of Minor Water Magic","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"0815b321e80803","name":"Elementalist Rune of Superior Air Magic","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"0815b321e80903","name":"Elementalist Rune of Superior Earth Magic","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"0815b321e80c03","name":"Elementalist Rune of Superior Energy Storage","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"0815b321e80a03","name":"Elementalist Rune of Superior Fire Magic","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"0815b321e80b03","name":"Elementalist Rune of Superior Water Magic","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"084adca5300406","name":"Forsaken Insignia [Dervish]","category":"runes","profession":"dervish","quantity":1}),
  Object.freeze({"modelId":"084ad5a53003f8","name":"Frostbound Insignia [Ranger]","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"084acaa53003e6","name":"Geomancer Insignia [Elementalist]","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"084adea530040a","name":"Ghost Forge Insignia [Ritualist]","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"084ac0a53003d4","name":"Herald's Insignia","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"084ac9a53003e4","name":"Hydromancer Insignia [Elementalist]","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"084ab5a53003be","name":"Infiltrator's Insignia [Assassin]","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"084ad0a53003f2","name":"Knight's Insignia [Warrior]","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"084ad127e802b6","name":"Lieutenant's Insignia [Warrior]","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"080e1c21e80202","name":"Mesmer Rune of Major Domination Magic","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"080e1c21e80002","name":"Mesmer Rune of Major Fast Casting","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"080e1c21e80102","name":"Mesmer Rune of Major Illusion Magic","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"080e1c21e80302","name":"Mesmer Rune of Major Inspiration Magic","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"08038321e80201","name":"Mesmer Rune of Minor Domination Magic","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"08038321e80001","name":"Mesmer Rune of Minor Fast Casting","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"08038321e80101","name":"Mesmer Rune of Minor Illusion Magic","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"08038321e80301","name":"Mesmer Rune of Minor Inspiration Magic","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"0815ad21e80203","name":"Mesmer Rune of Superior Domination Magic","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"0815ad21e80003","name":"Mesmer Rune of Superior Fast Casting","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"0815ad21e80103","name":"Mesmer Rune of Superior Illusion Magic","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"0815ad21e80303","name":"Mesmer Rune of Superior Inspiration Magic","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"084ac6a53003de","name":"Minion Master's Insignia [Necromancer]","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"0815b421e81002","name":"Monk Rune of Major Divine Favor","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"0815b421e80d02","name":"Monk Rune of Major Healing Prayers","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"0815b421e80f02","name":"Monk Rune of Major Protection Prayers","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"0815b421e80e02","name":"Monk Rune of Major Smiting Prayers","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"08038621e81001","name":"Monk Rune of Minor Divine Favor","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"08038621e80d01","name":"Monk Rune of Minor Healing Prayers","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"08038621e80f01","name":"Monk Rune of Minor Protection Prayers","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"08038621e80e01","name":"Monk Rune of Minor Smiting Prayers","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"0815b521e81003","name":"Monk Rune of Superior Divine Favor","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"0815b521e80d03","name":"Monk Rune of Superior Healing Prayers","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"0815b521e80f03","name":"Monk Rune of Superior Protection Prayers","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"0815b521e80e03","name":"Monk Rune of Superior Smiting Prayers","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"084adfa530040c","name":"Mystic's Insignia [Ritualist]","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"0815b021e80402","name":"Necromancer Rune of Major Blood Magic","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"0815b021e80702","name":"Necromancer Rune of Major Curses","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"0815b021e80502","name":"Necromancer Rune of Major Death Magic","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"0815b021e80602","name":"Necromancer Rune of Major Soul Reaping","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"08038421e80401","name":"Necromancer Rune of Minor Blood Magic","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"08038421e80701","name":"Necromancer Rune of Minor Curses","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"08038421e80501","name":"Necromancer Rune of Minor Death Magic","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"08038421e80601","name":"Necromancer Rune of Minor Soul Reaping","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"0815b121e80403","name":"Necromancer Rune of Superior Blood Magic","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"0815b121e80703","name":"Necromancer Rune of Superior Curses","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"0815b121e80503","name":"Necromancer Rune of Superior Death Magic","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"0815b121e80603","name":"Necromancer Rune of Superior Soul Reaping","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"084ab7a53003c2","name":"Nightstalker's Insignia [Assassin]","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"083cbd21e82602","name":"Paragon Rune of Major Command","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"083cbd21e82802","name":"Paragon Rune of Major Leadership","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"083cbd21e82702","name":"Paragon Rune of Major Motivation","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"083cbd21e82502","name":"Paragon Rune of Major Spear Mastery","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"083cbc21e82601","name":"Paragon Rune of Minor Command","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"083cbc21e82801","name":"Paragon Rune of Minor Leadership","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"083cbc21e82701","name":"Paragon Rune of Minor Motivation","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"083cbc21e82501","name":"Paragon Rune of Minor Spear Mastery","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"083cbe21e82603","name":"Paragon Rune of Superior Command","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"083cbe21e82803","name":"Paragon Rune of Superior Leadership","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"083cbe21e82703","name":"Paragon Rune of Superior Motivation","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"083cbe21e82503","name":"Paragon Rune of Superior Spear Mastery","category":"runes","profession":"paragon","quantity":1}),
  Object.freeze({"modelId":"084ac8a53003e2","name":"Prismatic Insignia [Elementalist]","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"084ab9a53003c6","name":"Prodigy's Insignia [Mesmer]","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"084ad7a53003fc","name":"Pyrebound Insignia [Ranger]","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"084acba53003e8","name":"Pyromancer Insignia [Elementalist]","category":"runes","profession":"elementalist","quantity":1}),
  Object.freeze({"modelId":"084abb253003ca","name":"Radiant Insignia","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0815b821e81602","name":"Ranger Rune of Major Beast Mastery","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"0815b821e81702","name":"Ranger Rune of Major Expertise","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"0815b821e81902","name":"Ranger Rune of Major Marksmanship","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"0815b821e81802","name":"Ranger Rune of Major Wilderness Survival","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"08038821e81601","name":"Ranger Rune of Minor Beast Mastery","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"08038821e81701","name":"Ranger Rune of Minor Expertise","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"08038821e81901","name":"Ranger Rune of Minor Marksmanship","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"08038821e81801","name":"Ranger Rune of Minor Wilderness Survival","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"0815b921e81603","name":"Ranger Rune of Superior Beast Mastery","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"0815b921e81703","name":"Ranger Rune of Superior Expertise","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"0815b921e81903","name":"Ranger Rune of Superior Marksmanship","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"0815b921e81803","name":"Ranger Rune of Superior Wilderness Survival","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"0818b821e82202","name":"Ritualist Rune of Major Channeling Magic","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"0818b821e82002","name":"Ritualist Rune of Major Communing","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"0818b821e82102","name":"Ritualist Rune of Major Restoration Magic","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"0818b821e82402","name":"Ritualist Rune of Major Spawning Power","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"0818b721e82201","name":"Ritualist Rune of Minor Channeling Magic","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"0818b721e82001","name":"Ritualist Rune of Minor Communing","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"0818b721e82101","name":"Ritualist Rune of Minor Restoration Magic","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"0818b721e82401","name":"Ritualist Rune of Minor Spawning Power","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"0818b921e82203","name":"Ritualist Rune of Superior Channeling Magic","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"0818b921e82003","name":"Ritualist Rune of Superior Communing","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"0818b921e82103","name":"Ritualist Rune of Superior Restoration Magic","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"0818b921e82403","name":"Ritualist Rune of Superior Spawning Power","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"08038225300423","name":"Rune of Attunement","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0815ae2530042b","name":"Rune of Clarity","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0815ae27e902c2","name":"Rune of Major Vigor","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"08038227e802c2","name":"Rune of Minor Vigor","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0815ae2530042d","name":"Rune of Purity","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0815ae25300427","name":"Rune of Recovery","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0815ae25300429","name":"Rune of Restoration","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"0815af27ea02c2","name":"Rune of Superior Vigor","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"08038225300425","name":"Rune of Vitae","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"084ab6a53003c0","name":"Saboteur's Insignia [Assassin]","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"084adaa5300402","name":"Scout's Insignia [Ranger]","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"084ad4a53003f6","name":"Sentinel's Insignia [Warrior]","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"084ac1a53003d6","name":"Sentry's Insignia","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"084adda5300408","name":"Shaman's Insignia [Ritualist]","category":"runes","profession":"ritualist","quantity":1}),
  Object.freeze({"modelId":"084abda53003ce","name":"Stalwart Insignia","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"084ad227e802b7","name":"Stonefist Insignia [Warrior]","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"084ad8a53003fe","name":"Stormbound Insignia [Ranger]","category":"runes","profession":"ranger","quantity":1}),
  Object.freeze({"modelId":"084abc253003cc","name":"Survivor Insignia","category":"runes","profession":"general","quantity":1}),
  Object.freeze({"modelId":"084ac3253003d8","name":"Tormentor's Insignia [Necromancer]","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"084ac4a53003da","name":"Undertaker's Insignia [Necromancer]","category":"runes","profession":"necromancer","quantity":1}),
  Object.freeze({"modelId":"084ab4a53003bc","name":"Vanguard's Insignia [Assassin]","category":"runes","profession":"assassin","quantity":1}),
  Object.freeze({"modelId":"084abaa53003c8","name":"Virtuoso's Insignia [Mesmer]","category":"runes","profession":"mesmer","quantity":1}),
  Object.freeze({"modelId":"084acda53003ec","name":"Wanderer's Insignia [Monk]","category":"runes","profession":"monk","quantity":1}),
  Object.freeze({"modelId":"0815b627e902ea","name":"Warrior Rune of Major Absorption","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"0815b621e81202","name":"Warrior Rune of Major Axe Mastery","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"0815b621e81302","name":"Warrior Rune of Major Hammer Mastery","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"0815b621e81102","name":"Warrior Rune of Major Strength","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"0815b621e81402","name":"Warrior Rune of Major Swordsmanship","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"0815b621e81502","name":"Warrior Rune of Major Tactics","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"08038727e802ea","name":"Warrior Rune of Minor Absorption","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"08038721e81201","name":"Warrior Rune of Minor Axe Mastery","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"08038721e81301","name":"Warrior Rune of Minor Hammer Mastery","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"08038721e81101","name":"Warrior Rune of Minor Strength","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"08038721e81401","name":"Warrior Rune of Minor Swordsmanship","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"08038721e81501","name":"Warrior Rune of Minor Tactics","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"0815b727ea02ea","name":"Warrior Rune of Superior Absorption","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"0815b721e81203","name":"Warrior Rune of Superior Axe Mastery","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"0815b721e81303","name":"Warrior Rune of Superior Hammer Mastery","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"0815b721e81103","name":"Warrior Rune of Superior Strength","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"0815b721e81403","name":"Warrior Rune of Superior Swordsmanship","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"0815b721e81503","name":"Warrior Rune of Superior Tactics","category":"runes","profession":"warrior","quantity":1}),
  Object.freeze({"modelId":"084adba5300404","name":"Windwalker Insignia [Dervish]","category":"runes","profession":"dervish","quantity":1}),
]);

export function traderItem(modelId: string): TraderItem | undefined {
  return TRADER_ITEMS.find((item) => item.modelId === modelId);
}
